textbox("sprite animation test")
textbox("death")
animate_sprite("testsprite1", "death")
wait(0.2)

textbox("reset")
animate_sprite("testsprite1", "RESET")
wait(0.2)

textbox("facing directions")
animate_sprite("testsprite1", "face_up", "up")
wait(0.5)
animate_sprite("testsprite1", "face_down", "down")
wait(0.5)
animate_sprite("testsprite1", "face_left", "left")
wait(0.5)
animate_sprite("testsprite1", "face_right", "right")
wait(0.5)

textbox("walking directions")
animate_sprite("testsprite1", "walk_up", "up")
wait(0.5)
animate_sprite("testsprite1", "walk_down", "down")
wait(0.5)
animate_sprite("testsprite1", "walk_left", "left")
wait(0.5)
animate_sprite("testsprite1", "walk_right", "right")
wait(0.5)

textbox("attack directions")
animate_sprite("testsprite1", "attack_up", "up")
wait(0.5)
animate_sprite("testsprite1", "attack_down", "down")
wait(0.5)
animate_sprite("testsprite1", "attack_left", "left")
wait(0.5)
animate_sprite("testsprite1", "attack_right", "right")
wait(0.5)
