local modname = core.get_current_modname()
local S = core.get_translator(modname)

return {
	{S("Creators of Mineclonia"), 0x0A9400, {
		"ryvnf",
		"cora",
	}},
	{S("Creator of MineClone 2"), 0xFFFFFF, {
		"Wuzzy",
	}},
	{S("Creator of MineClone"), 0xFF51D5, {
		"davedevils",
	}},
	{S("Active Contributors"), 0xF84355, {
		"Brama Udi",
		"ellesheepy",
		"Jürgen Rühle",
		"Po Lu",
		"JoseDouglas26",
		"Raylight",
		"Miguel_PL",
		"B. Stack",
		"cosinus",
		"Codiac",
		"xox",
		"Marek Jędrzejewski",
		"amino",
		"epCode",
		"hezemisverydumb",
	}},
	{S("Previous Contributors"), 0x52FF00, {
		"Lizzy Fleckenstein",
		"AFCMS",
		"NO11",
		"Brandon",
		"kay27",
		"marcin-serwin",
		"Michieal",
		"epCode",
		"PrairieWind",
		"chmodsayshello",
		"iliekprogrammar",
		"ancientmarinerdev",
		"TheOnlyJoeEnderman",
		"jordan4ibanez",
		"FossFanatic",
		"rubenwardy",
		"SumianVoice",
		"MysticTempest",
		"HimbeerserverDE",
		"MrRar",
		"kabou",
		"FaceDeer",
		"ChrisPHP",
		"3raven",
		"ShadowRoi",
		"amino",
		"teknomunk",
		"laireia",
		"Eliy21",
		"ROllerozxa",
		"BlockMen",
		"debiankaios",
		"debian044",
		"zitanyang",
		"Code-Sploit",
		"Rootyjr",
		"codiac",
		"kno10",
		"Lars Müller",
		"the-real-herowl",
		"DragonWrangler1",
		"Mikita Wiśniewski",
		"nooneatall",
		"nixnoxus",
		"Ælla Chiana Moskopp",
	}},
	{S("Original Mod Authors"), 0xA60014, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"cora",
	}},
	{S("3D Models"), 0x343434, {
		"22i",
		"tobyplowy",
		"epCode",
		"pixelzone",
	}},
	{S("Textures and menu images"), 0x0019FF, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Michieal",
		"ryvnf",
		"SmokeyDope",
		"Aeonix_Aeon",
		"Nicu",
		"Exhale",
		"Aeonix_Aeon",
		"Wbjitscool",
		"SmokeyDope",
		"pixelzone",
		"Miguel P.L",
	}},
	{S("Translations"), 0xFF9705, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"Riu Sakura",
		"3raven",
		"Ame-chan-angel",
		"Application-Maker",
		"Benny",
		"collectanos",
		"Cwpute",
		"Dirk",
		"Enlive",
		"fnetX",
		"Gaemy",
		"hugoalh",
		"j-r",
		"Kyoushi",
		"liulitchi",
		"mugcake",
		"phileas",
		"Pietro Cappuccino",
		"RadonPrunus",
		"Sencyy",
		"Sotis",
		"Zozosticot",
		"ellesheepy",
		"bright",
		"Miguel P.L",
		"Just Playing",
		"bramaudi",
		"balazsszalab",
		"milklikecomputer",
		"CodePoet2005",
		"real_mineplayer",
		"3raven",
		"Ame-chan-angel",
		"Benny",
		"bramaudi",
		"bright",
		"collectanos",
		"Cwpute",
		"Dirk",
		"ellesheepy",
		"Enlive",
		"fnetX",
		"Gaemy",
		"hugoalh",
		"j-r",
		"Just Playing",
		"Kyoushi",
		"liulitchi",
		"metmj",
		"Miguel P.L",
		"Miguel_PL",
		"milklikecomputer",
		"mugcake",
		"Oldcoinmania",
		"phileas",
		"Pietro Cappuccino",
		"RadonPrunus",
		"Sencyy",
		"Sotis",
		"wilker",
		"XP_42319",
		"Zozosticot",
	}},
	{S("Special thanks"), 0x00FF60, {
		"celeron55 for creating Luanti (Minetest)",
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"The workaholics who spent way too much time writing for the Minecraft Wiki.",
		"Notch and Jeb for being the major forces behind Minecraft",
	}},
}
