#!/bin/bash

# unpack the installer if it exists
chasm_gog_installer=$(ls chasm_*.sh 2>/dev/null | head -n 1)
if [ -n "$chasm_gog_installer" ]; then
    unzip "$chasm_gog_installer"
    cp -r data/noarch/game/* .
    # clean up only the extracted script and installer files
    rm -rf "$chasm_gog_installer" data meta scripts
fi
