(tecnoballz-config
	;; the following options can be set to #t or #f:
	(fullscreen #f)
	(sound #t)
	(verbose #f)

	;; window size 1 (low-res) or 2 (high-res):
	(resolution  1)

	;; difficulty 1 (easy), 2 (hard), 3 (madness) or 4 (suicidal)
	(difficulty   1)

	;; number of lives (1 to 9)
	(lives   8)

	;; number of players (1 to 6)
	(players   1)

	;; players names
	(player1      "PORTMA")
	(player2      "BUBUX2")
	(player3      "BUBUX4")
	(player4      "BUBUX5")
	(player5      "BUBUX6")
	(player6      "BUBUX7")
)
