#!/bin/bash

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

DATADIR=$GAMEDIR/gamedata
TEMPDIR=$GAMEDIR/tmp

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

echo $DATADIR

# Extract if necessary and possible
mkdir -p $TEMPDIR
cd $TEMPDIR

gog_file=`find $DATADIR -name "dicey_dungeons*.sh"`
if [ ! -z "$gog_file" ]; then
  echo $gog_file
  export LD_LIBRARY_PATH=$GAMEDIR/tools/libs.aarch64:$LD_LIBRARY_PATH
  $GAMEDIR/tools/unzip $gog_file
  mv data/noarch/game/* $DATADIR
fi

if [ -f $DATADIR/diceydungeons ]; then
  rm $DATADIR/$gog_file
  rm -r $DATADIR/goggame*
fi

rm -r $TEMPDIR
