#!/bin/bash

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

SRCDIR=$GAMEDIR/gamedata
TEMPDIR=$GAMEDIR/tmp
DESTDIR=$GAMEDIR/gamedata

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

echo $SRCDIR

# Extract if necessary and possible
mkdir -p $TEMPDIR
cd $TEMPDIR

gog_file=`find $SRCDIR -name "dicey_dungeons*.sh"`
if [ ! -z "$gog_file" ]; then
  echo $gog_file
  unzip $gog_file
  mv data/noarch/game/* $DESTDIR
  rm $gog_file
fi

rm -r $TEMPDIR
rm -r $DESTDIR/*.sh $DESTDIR/goggame*
