[config]
deadzone_triggers = 3000
mouse_scale = 6114
mouse_delay = 14
mouse_slow_scale = 30

deadzone_mode = axial
deadzone = 8000
deadzone_scale = 8
deadzone_delay = 16

[controls]
overlay = clear

up = up
down = down
left = left
right = right

a = 0
b = 1
x = 2
y = 3
l1 = 4
r1 = 5
l2 = 6
r2 = 7
l3 = 8
r3 = 9

# start is normally "enter", but holding it down uses it as a hotkey
start = enter hold_state hotkey
select = shift
guide = esc

left_analog_up = up
left_analog_down = down
left_analog_left = left
left_analog_right = right
right_analog_up = \"
right_analog_down = \"
right_analog_left = \"
right_analog_right = \"

[controls:hotkey]
overlay = clear

# hold start and tap menu to enter the password entry mode
guide = push_state passwords

[controls:passwords]
overlay = clear

# enter characters by using any of the following mappings
# this mapping ATTEMPTS to cover all of the required letters
# while also being somewhat memorable

# compass directions
up = n
down = s
right = e
left = w

# self-explanatory
a = a
b = b
x = x
y = y

# l->m r->s
l1 = l
l2 = m
r1 = r
r2 = s

# uh... confirm / option ?
start = c
select = o

# tap menu to exit the password entry mode
guide = pop_state