Profile
Name PortMaster
OwnDeaths 0
CloneMurders 0
ClonesCreated 0
SwapperShotsFired 0
TimeInMenus 84.40551
TimeInGame 309.5195
SubtitlesEnabled False
AudioEnabled True
AudioVolume 1
AudioMusicVolume 0.75
AudioEffectVolume 1
AudioAtmosphereVolume 1
MaxAudioChannels 24
IsFullscreen True
ShadowQuality 1
DiffuseQuality 1
ParticleQuality 1
IsFilmlookEnabled False
IsPostFxEnabled False
PostFxBlurQuality 0
PostFxMotionBlurQuality False
PostFxBloomQuality 0
LightShaftQuality 1
GBufferSampleAntialising 1
Dithering False
Vignette 0
HiResEdges False
IsVsyncEnabled False
XResolution 640
YResolution 480
SmoothSampling False
Antialising False
ScreenRefreshRate 60
ScreenRefreshRateCapEnabled False
ScreenRefreshRateCap 60
DisableCustomMouseSensitivity False
MouseSpeed 1
Space 51|1
W 105|1
A 83|1
S 101|1
D 86|1
E 87|1
Q 99|1
F 88|1
Esc 50|1
MouseLeft 0|0
MouseRight 2|0
Pad_Left 83|1
Pad_Right 86|1
Pad_Up 105|1
Pad_Down 101|1
Pad_A 51|1
Pad_B 99|1
Pad_X 87|1
Pad_Y 88|1
Pad_ShoulderLeft 2|0
Pad_ShoulderRight 0|0
Pad_Start 50|1
Pad_Back 107|1
Pad_TriggerLeft 2|0
Pad_TriggerRight 0|0
Pad_StickLeft 0|1
Pad_StickRight 0|1
Pad_ThumbstickUp 105|1
Pad_ThumbstickDown 101|1
Pad_ThumbstickLeft 83|1
Pad_ThumbstickRight 86|1
Pad_InvertLeftThumbstickY False
Pad_InvertRightThumbstickY False
Pad_UseRightThumbstickForMovement False
Pad_ThumbstickSensitivity 1
Pad_DeadZone 0.25
Pad_Scheme 0
Pad_AimAssist True
ServerPort 4321
ClientPort 4322
PlaytestScreenCaptureDisabled True
RecordingModeEnabled False
CrashReporterEnabled False
OptimusRestarted False
HasBeenInitialized True
