--[[Autogenerated rockbox constants]]

rb.sound_settings = rb.sound_settings or {}
rb.sound_settings["SOUND_BALANCE"] = 1
rb.sound_settings["SOUND_CHANNELS"] = 2
rb.sound_settings["SOUND_STEREO_WIDTH"] = 3
rb.sound_settings["SOUND_VOLUME"] = 0
