[config]
deadzone_mode = axial
deadzone = 3000
deadzone_scale = 7
deadzone_delay = 16

[controls]

overlay = controls

start = enter

l1 = e        # Left door
r1 = i          # Right door
l2 = f          # Left light
r2 = j          # Right light

#Pan Office
left_analog_left = a 
left_analog_right = d 

a = g         # Open cams
b = h         # Close cams

# Mute call - Step 3/6
y = m

# Camera navigation Arrow Keys
up = up
down = down
left = left
right = right
