#!/bin/bash

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt
export PORT_32BIT="Y"
[[ "${CFW_NAME^^}" == 'MUOS' ]] && directory=$(realpath "$0" | sed 's|^\./||' | awk -F'/' '{print "/" $2 "/" $3}')
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
get_controls

GAMEDIR="/$directory/ports/firearrow/firearrow"

export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$LD_LIBRARY_PATH"
export GMLOADER_DEPTH_DISABLE=1
export GMLOADER_SAVEDIR="$GAMEDIR/gamedata/"
export GMLOADER_PLATFORM="os_linux"

cd "$GAMEDIR"

> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1

if [ -f "$GAMEDIR/gamedata/data.win" ]; then
    mv "$GAMEDIR/gamedata/data.win" "$GAMEDIR/gamedata/game.droid"
    sleep 0.5
    mkdir -p $GAMEDIR/assets
    mv $GAMEDIR/gamedata/*.ogg $GAMEDIR/assets/ 
    mv $GAMEDIR/gamedata/game.droid $GAMEDIR/assets/ 
    sleep 0.5
    zip -r -0 ./firearrow.port assets lib
    rm -rf "$GAMEDIR/assets"
    rm -rf "$GAMEDIR/gamedata"
    rm -rf "$GAMEDIR/lib"
fi

$GPTOKEYB "gmloader" &
pm_message "Loading, please wait... " > /dev/tty0

$ESUDO chmod +x "$GAMEDIR/gmloader"
pm_platform_helper "$GAMEDIR/gmloader"
./gmloader firearrow.port

pm_finish
