Put files into this directory (use <Map author="Anonymous" ...>)
if, for some reason, you don't want credit for it. This can be because
- no real creative process was involved (like the square maps)
- they were generated by a program, not yourself (like a maze generator)
- they cannot be copyrighted or you don't want them copyrighted
- they do not meet your usual quality standards
but in no way, under no circumstances, will we force you to put your
files here.

The comments in the file can still state that you are the author, and
state the license. The minimal license for resources obviously should
be "use freely as long as you don't modify the file", but for
anonymous files, putting them into the public domain is recommended
so others can adapt them to new game versions.
