#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"
LOGERR="$GAMEDIR/patch_error.txt"

# Redirect output and error to the log file
rm -rf $LOGFILE $LOGERR
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="haque.port"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

PYTHON=$(which python3)

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

prepare_files() {
    # Delete unnecessary files
    rm -rf $DATADIR/*.so $DATADIR/*.exe $DATADIR/*.dll $DATADIR/.gitkeep $DATADIR/gamedat $DATADIR/runner
    echo "Removed unnecessary files"
    if [ -f "$DATADIR/data.win" ]; then
        mv "$DATADIR/data.win" "$DATADIR/game.droid"
    elif [ -f "$DATADIR/game.unx" ]; then
        mv "$DATADIR/game.unx" "$DATADIR/game.droid"
    fi
    
    # Edit options.ini
    if [ -f "$DATADIR/options.ini" ]; then
        if grep -q '^CreateTexturesOnDemand=' "$DATADIR/options.ini"; then
            sed -i 's/^CreateTexturesOnDemand=.*/CreateTexturesOnDemand=1/' "$DATADIR/options.ini"
        else
            echo 'CreateTexturesOnDemand=1' >> "$DATADIR/options.ini"
        fi
    else
        echo "Error: options.ini missing!"
        mv "$PATCHLOG" "$PATCHERR"
        exit 1
    fi
    sleep 1

    # Unzip the Haque_Text.zip file if it exists (case-insensitive)
    file=$(find "$DATADIR" -iname "Haque_Text.zip" | head -n 1)

    if [ -n "$file" ]; then
        unzip "$file" -d "$DATADIR"
        find "$DATADIR/Haque_Text" -type f -exec dos2unix -u {} \;
        rm -rf "$file"
    else
        echo "Couldn't find Haque_Text.zip! Game will not run!"
        sleep 2
        exit
    fi
}

compress_audio() {
    echo "Compressing audio..."
    # Clear out the temporary directory
    mkdir -p "$TMPDIR"
    rm -rf $TMPDIR/*

    # Run the compression tool
    echo "Running GMTools on data and audiogroups."
    $PYTHON $TOOLDIR/gmKtool.py -vv -c 6 -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$DATADIR"
        echo "Moved compressed files to $DATADIR."
        rm -rf "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
        sleep 1
    else
        echo "Audio compression failed."
        echo "Cleaning up temporary directory $TMPDIR."
        rm -rf "$TMPDIR"
        sleep 1
    fi
}

zip_archive() {
        echo "Finishing up..."
        zip -r -0 $DATAFILE ./assets/
        mkdir -p saves
        rm -rf $DATADIR/*
        sleep 1
}

process_game() {
    prepare_files
    compress_audio
    zip_archive
	
    # Final completion message
    echo "Patching process complete!"
}

process_game
