textbox_portrait_right("lilu", true)
textbox("You didn't have to come...", "Lilu")
textbox("As a former stray I know a thing or two about these cats, and they are no match for me!", "Lilu")
textbox_portrait_right()

textbox_portrait_left("sprinkles", true)
textbox("You are no longer a stray, Lilu. You are a member of our family now, and no longer alone.", "Sprinkles")
textbox("We have your back, now join us with our fight against the Black Cats!", "Sprinkles")
textbox_portrait_left()

textbox_portrait_right("lilu", true)
textbox("...", "Lilu")
textbox("Sprinkles, I owe you one. I'm going to fight by your side from now on.", "Lilu")
textbox_portrait_right()
hide_textbox()
