textbox_portrait_right("sabu", true)
textbox("Sprinkles!?", "Sabu")
textbox("You came to save me..?", "Sabu")
textbox("These scary looking cats were saying so many mean things about you, about how you are invading everyone's territory.", "Sabu")
textbox("They wouldn't listen to me!", "Sabu")
textbox_portrait_right()

textbox_portrait_left("sprinkles", true)
textbox("It's a group of rascals known as the Black Cats, causing all sorts of havoc in this area as of late.", "Sprinkles")
textbox("We're all here now in search of their hideout, would you join us?", "Sprinkles")
textbox_portrait_left()

textbox_portrait_right("sabu", true)
textbox("I'm not much of a fighter, but I'll do what I can to help you, my brother!", "Sabu")
textbox_portrait_right()
hide_textbox()
