local entity_stub = { on_activate = function(self)
	core.log("warning", "Leftover entity from VoxeLibre "..tostring(self.name).." at "..core.pos_to_string(self.object:get_pos() ,0)..". Removing it.")
	return self.object:remove()
end, }
local unique_vl_entities = {
	"mcl_potions:darkness_arrow_entity",
	"mobs_mc:rover",
	"vl_fireworks:rocket",
	"mcl_potions:glowing_splash_flying",
	"mcl_potions:glowing_lingering_flying",
	"mcl_potions:resistance_arrow_entity",
	"mcl_potions:trolling_lingering_flying",
	"mcl_potions:saturation_splash_flying",
	"vl_held_item:held_item_entity",
	"mcl_potions:haste_splash_flying",
	"mcl_potions:saturation_lingering_flying",
	"mcl_potions:food_poisoning_arrow_entity",
	"mcl_potions:absorption_splash_flying",
	"mcl_potions:resistance_lingering_flying",
	"mcl_potions:nausea_arrow_entity",
	"mcl_potions:nausea_lingering_flying",
	"mcl_potions:blindness_arrow_entity",
	"mcl_potions:nausea_splash_flying",
	"mcl_potions:frost_arrow_entity",
	"mcl_potions:resistance_splash_flying",
	"mcl_potions:frost_splash_flying",
	"mcl_potions:stone_cloak_arrow_entity",
	"mcl_potions:stone_cloak_lingering_flying",
	"mcl_potions:stone_cloak_splash_flying",
	"mcl_potions:food_poisoning_splash_flying",
	"mcl_potions:frost_lingering_flying",
	"mcl_potions:absorption_arrow_entity",
	"mcl_potions:absorption_lingering_flying",
	"mcl_potions:food_poisoning_lingering_flying",
	"mcl_potions:health_boost_lingering_flying",
	"mcl_potions:levitation_arrow_entity",
	"mcl_potions:health_boost_splash_flying",
	"mcl_potions:darkness_lingering_flying",
	"mcl_potions:health_boost_arrow_entity",
	"mobs_mc:potion_arrow",
	"mcl_potions:levitation_lingering_flying",
	"mcl_potions:blindness_splash_flying",
	"mcl_bows:rocket_entity",
	"mcl_potions:blindness_lingering_flying",
	"vl_weaponry:spear_entity",
	"mobs_mc:stalker",
	"mcl_potions:saturation_arrow_entity",
	"mcl_potions:haste_lingering_flying",
	"mcl_potions:trolling_arrow_entity",
	"mcl_potions:trolling_splash_flying",
	"mcl_potions:levitation_splash_flying",
	"mcl_potions:haste_arrow_entity",
	"mobs_mc:elemental_fire",
	"mcl_potions:fatigue_splash_flying",
	"mcl_potions:fatigue_lingering_flying",
	"mobs_mc:stalker_overloaded",
	"mcl_potions:darkness_splash_flying",
	"mobs_mc:small_fireball",
	"mcl_potions:fatigue_arrow_entity",
	"mobs_mc:baby_zombified_piglin",
}

for _, name in pairs(unique_vl_entities) do
	core.register_entity(":"..name, entity_stub)
end
