.\" This program is free software;  you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hop that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
.
.TH AMOEBAX 6 "2007" "amoebax" "Amoebax"
.
.SH NAME
amoebax \- Match-3 action-puzzle game
.
.SH SYNOPSIS
.
.B amoebax
[\fIOPTIONS\fR]
.
.SH DESCRIPTION
.
Amoebax is a match-3 action-puzzle game.

Defeat your opponents by filling up her grid.  To fill your opponent's
grid you need to join four or more amoebas of the same color either
horizontally, vertically or a combination of the two but not in diagonal.

Play either as Kim or Tim in against six computer controlled opponents or
challenge your friends in a tournament.  If you just want to relax, try
the training mode at your own pace.
.
.SH OPTIONS
.
.TP
.
.BI -f ", " --fullscreen
Starts the game in full screen mode.
.TP
.BI --enable-sound
Enables the sound and music but does not modify the volume level.
.TP
.BI --disable-sound
Disables the sound and music.  The volume level will stay at zero.
.TP
.BI -h ", " --help
Displays a help message with the available options.
.TP
.BI -V ", " --version
Prints the version information.
.TP
.BI -w ", " --windowed
Starts the game in windowed mode instead of full screen.
.
.SH AUTHOR
Written by Jordi Fita <jordi@emma-soft.com>
.
.SH COPYRIGHT
.
Copyright \(co 2006-2007 Emma's Software <jordi@emma-soft.com>
.br
This is Free Software; this software is licensed under the GPL version 2, as published by the Free Software Foundation.
There is NO WARRANTY; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

