## Copyright 2000, 2001  Alexandre Duret-Lutz <duret_g@epita.fr>
##
## This file is part of Heroes.
##
## Heroes is free software; you can redistribute it and/or modify it under
## the terms of the GNU General Public License as published by the Free
## Software Foundation; either version 2 of the License, or (at your
## option) any later version.
##
## Heroes is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
## FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
## for more details.
##
## You should have received a copy of the GNU General Public License along
## with this program; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

levelsdir  = $(datadir)/heroes/levels

levels_DATA = \
levels/level.lst \
levels/niv010.lvl \
levels/niv011.lvl \
levels/niv012.lvl \
levels/niv013.lvl \
levels/niv014.lvl \
levels/niv015.lvl \
levels/niv016.lvl \
levels/niv017.lvl \
levels/niv018.lvl \
levels/niv019.lvl \
levels/niv020.lvl \
levels/niv021.lvl \
levels/niv022.lvl \
levels/niv023.lvl \
levels/niv024.lvl \
levels/niv025.lvl \
levels/niv026.lvl \
levels/niv027.lvl \
levels/niv028.lvl \
levels/niv029.lvl \
levels/niv030.lvl \
levels/niv031.lvl \
levels/niv032.lvl \
levels/niv033.lvl \
levels/niv034.lvl \
levels/niv035.lvl \
levels/niv036.lvl \
levels/niv037.lvl \
levels/niv038.lvl \
levels/niv039.lvl \
levels/niv040.lvl \
levels/niv041.lvl \
levels/niv042.lvl \
levels/niv043.lvl \
levels/niv044.lvl \
levels/niv045.lvl \
levels/niv046.lvl \
levels/niv047.lvl \
levels/niv048.lvl \
levels/niv049.lvl \
levels/niv050.lvl \
levels/niv051.lvl \
levels/niv052.lvl \
levels/niv053.lvl \
levels/niv054.lvl \
levels/niv055.lvl \
levels/niv056.lvl \
levels/niv057.lvl \
levels/niv058.lvl \
levels/niv059.lvl \
levels/niv060.lvl \
levels/niv061.lvl \
levels/niv062.lvl \
levels/niv063.lvl \
levels/niv064.lvl \
levels/niv065.lvl \
levels/niv066.lvl \
levels/niv067.lvl \
levels/niv068.lvl \
levels/niv070.lvl \
levels/niv071.lvl \
levels/niv072.lvl \
levels/niv073.lvl \
levels/niv074.lvl \
levels/niv075.lvl \
levels/niv076.lvl \
levels/niv077.lvl \
levels/niv078.lvl \
levels/niv080.lvl \
levels/niv081.lvl \
levels/niv082.lvl \
levels/niv083.lvl \
levels/niv084.lvl \
levels/niv085.lvl \
levels/niv086.lvl \
levels/niv087.lvl \
levels/niv088.lvl \
levels/niv090.lvl \
levels/niv091.lvl \
levels/niv092.lvl \
levels/niv093.lvl \
levels/niv094.lvl \
levels/niv095.lvl \
levels/niv096.lvl \
levels/niv097.lvl \
levels/niv100.lvl \
levels/niv101.lvl \
levels/niv102.lvl \
levels/niv103.lvl \
levels/niv104.lvl \
levels/niv105.lvl \
levels/niv106.lvl \
levels/niv107.lvl \
levels/niv108.lvl

EXTRA_DIST += $(levels_DATA)
