[paths]

game_files="./gamedata/"
support_files="./gamedata/"

android_package_code="./"
android_external_files="../conf/"
android_files="../conf/"
android_cache="../cache/"
android_obb_dirs=["./gamedata/"]
android_source_dirs=["./gamedata/"]


[package]

packageName="com.Koksny.WhichSausageMate"
versionName="1.0.3"
mainIntentBundle = { unity = "" }


[device]

displayWidth=1280
displayHeight=720
displayRotation=0

[input]
controller=true
