#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/gamedata"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

# If "gamedata/data.win" exists and matches the checksum of the Steam or Itch versions
if [ -f "./gamedata/data.win" ]; then
    checksum=$(md5sum "./gamedata/data.win" | awk '{print $1}')
    
    # Checksum for the Steam version
    if [ "$checksum" = "9f12bbf6e23626fdb69782f6ecaa4a6b" ]; then
        mv "./patch/game.apk.steam" "./game.apk"
        mv "./gamedata/data.win" "./gamedata/game.droid"
        rm -f "./patch/game.apk.itch"
        echo "steam version detected, data.win renamed to game.droid"
    # Checksum for the Itch version
    elif [ "$checksum" = "7442951ac2c5f1e8d29242f2d3a9e12c" ]; then
        mv "./patch/game.apk.itch" "./game.apk"
        mv "./gamedata/data.win" "./gamedata/game.droid"
        rm -f "./patch/game.apk.steam"
        echo "itch.io version detected, data.win renamed to game.droid"
    else
        echo "Error: MD5 checksum of data.win does not match any expected version."
	exit 1
    fi
else    
    echo "Missing files in gamedata folder or game has been patched."
fi

# Compress audio
echo "Compressing audio..."
sleep 3
mkdir -p "$TMPDIR"

# Run the compression tool
PYTHON=$(which python3)
$PYTHON ./tools/gmKtool.py -vvv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"

if [ $? -eq 0 ]; then
    echo "Compression completed successfully."
    mv "$TMPDIR/"* "$DATADIR"
    echo "Moved compressed files to $DATADIR."
    rmdir "$TMPDIR"
    echo "Temporary directory $TMPDIR removed."
    echo "Audio compression applied successfully."
else
    echo "Audio compression failed."
    echo "Cleaning up temporary directory $TMPDIR."
    rm -rf "$TMPDIR"
fi

# Check if either "Tamiku.exe"exists
if [ -f "./gamedata/Tamiku.exe" ]; then    
    # Remove extra files from Steam build
    rm -Rf "./gamedata/Tamiku.exe" \
           "./gamedata/"*.dll \
	   "./gamedata/Place game files here" 
    echo "Extra game files removed"
else    
    echo "No extra game files to remove, game has been patched!"
fi