name: PortMaster GUI Issue
description: Report a problem with the PortMaster GUI tool.
labels: 
  - portmaster-gui
title: '[PortMaster GUI]: '

body:
  - type: markdown
    attributes:
      value: "## Please include your `pugwash.txt` file!"

  - type: input
    id: device_type
    attributes:
      label: "Device Type"
      description: "Please specify the type of device you're using (e.g. RG35XXSP)."

  - type: dropdown
    id: firmware
    attributes:
      label: "Firmware"
      description: "Select the firmware you were using when you encountered the problem. If you tried multiple, select all that apply."
      options:
        - "ArkOS"
        - "ArkOS Wummle"
        - "ArkOS AeolusUX"
        - "AmberELEC"
        - "JelOS"
        - "Rocknix"
        - "uOS"
        - "RetroOZ"
        - "TheRA"
        - "muOS"
        - "Knulli"
        - "Crossmix"
        - "Batocera"
      multiple: true

  - type: checkboxes
    id: gui_track
    attributes:
      label: "GUI Track"
      description: "Which track are you using?"
      options:
        - label: "Release"
        - label: "Beta"

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the problem you encountered."

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Reproduction Steps"
      description: "List the steps to reproduce the problem."
