name: Port Issue
description: Report a problem with a specific port.
labels: 
  - port issue
title: '[Port Issue]: '

body:
  - type: markdown
    attributes:
      value: "## Remember to upload any `log.txt` files you have!"

  - type: input
    id: device_type
    attributes:
      label: "Device Type"
      description: "Please specify the type of device you're using (e.g. RG35XXSP)."

  - type: dropdown
    id: firmware
    attributes:
      label: "Firmware"
      description: "Select the firmware you were using when you encountered the problem. If you tried multiple, select all that apply."
      options:
        - "ArkOS"
        - "ArkOS Wummle"
        - "ArkOS AeolusUX"
        - "AmberELEC"
        - "JelOS"
        - "Rocknix"
        - "uOS"
        - "RetroOZ"
        - "TheRA"
        - "muOS"
        - "Knulli"
        - "Crossmix"
        - "Batocera"
      multiple: true

  - type: input
    id: port_name
    attributes:
      label: "Port Name"
      description: "Specify the name of the port you are reporting an issue for."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the problem you encountered."

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Please provide additional information including the game assets and version you used if applicable as well as the contents of relevant logs including log.txt and patchlog.txt."
      
  - type: markdown
    attributes:
      value: "### ⚠️ Before submitting this issue, please read your log files and port instructions thoroughly to determine if the issue is user-error."
