title = Mineclonia
description = A survival sandbox game. Survive, gather, hunt, build, explore, and do much more.
textdomain = mcl_game_meta
disallowed_mapgens = v6
first_mod = mcl_init
last_mod = _mcl_autogroup
min_minetest_version = 5.10
release = 35133
author = ryvnf
