#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Permissions
chmod 666 /dev/uinput

cd "$GAMEDIR"

echo Extracting game data...
# print every 100th line; otherwise patcher slows down
gunzip gamedata.tar.gz
tar -xvf gamedata.tar | awk 'NR % 100 == 0'
rm gamedata.tar gamedata.tar.gz
