#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

exec > >(tee -a "$LOGFILE") 2>&1

set -e

unpack_apk() {
    mkdir -p "$GAMEDIR/.apktemp" &&
    unzip -o "$GAMEDIR/*.apk" -d "$GAMEDIR/.apktemp"

    # Move lib/arm64-v8a contents to GAMEDIR
    rsync -a "$GAMEDIR/.apktemp/lib/arm64-v8a/" "$GAMEDIR/"
 
    # Move assets
    rsync -a "$GAMEDIR/.apktemp/assets/" "$GAMEDIR/gamedata/" && 
        rm "$GAMEDIR/"*.apk && rm -rf "$GAMEDIR/.apktemp"

}

unpack_obb() {
    mkdir -p "$GAMEDIR/gamedata"
    unzip -o "$GAMEDIR/*.obb" -d "$GAMEDIR/.obbtemp"
    rsync -a "$GAMEDIR/.obbtemp/" "$GAMEDIR/gamedata/" && rm "$GAMEDIR/"*.obb && rm -rf "$GAMEDIR/.obbtemp"
}

apk_count=$(ls -1 "$GAMEDIR/"*.apk 2>/dev/null | wc -l)
if [ "$apk_count" -gt 0 ]; then
    unpack_apk
fi

obb_count=$(ls -1 "$GAMEDIR/"*.obb 2>/dev/null | wc -l)
if [ "$obb_count" -gt 0 ]; then
    unpack_obb
fi
