local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
	{S("Creators of Mineclonia"), 0x0A9400, {
		"ryvnf",
		"cora",
	}},
	{S("Creator of MineClone 2"), 0xFFFFFF, {
		"Wuzzy",
	}},
	{S("Creator of MineClone"), 0xFF51D5, {
		"davedevils",
	}},
	{S("Active Contributors"), 0xF84355, {
		"codiac",
		"ShadowRoi",
		"nixnoxus",
		"chmodsayshello",
		"laireia",
		"nixnoxus",
		"the-real-herowl",
		"JoseDouglas26",
		"Eliy21",
	}},
	{S("Previous Contributors"), 0x52FF00, {
		"Lizzy Fleckenstein",
		"AFCMS",
		"NO11",
		"Brandon",
		"kay27",
		"marcin-serwin",
		"Michieal",
		"epCode",
		"PrairieWind",
		"iliekprogrammar",
		"ancientmarinerdev",
		"TheOnlyJoeEnderman",
		"jordan4ibanez",
		"FossFanatic",
		"rubenwardy",
		"SumianVoice",
		"MysticTempest",
		"HimbeerserverDE",
		"MrRar",
		"kabou",
		"FaceDeer",
		"Nils Dagsson Moskopp",
		"ChrisPHP",
		"3raven",
	}},
	{S("Original Mod Authors"), 0xA60014, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"cora",
	}},
	{S("3D Models"), 0x343434, {
		"22i",
		"tobyplowy",
		"epCode",
	}},
	{S("Textures and menu images"), 0x0019FF, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Michieal",
		"ryvnf",
		"SmokeyDope",
		"Aeonix_Aeon",
		"Nicu",
		"Exhale",
		"Aeonix_Aeon",
		"Wbjitscool",
		"SmokeyDope",
	}},
	{S("Translations"), 0xFF9705, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"Riu Sakura",
	}},
	{S("Special thanks"), 0x00FF60, {
		"celeron55 for creating Minetest",
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"The workaholics who spent way too much time writing for the Minecraft Wiki.",
		"Notch and Jeb for being the major forces behind Minecraft",
	}},
}
