#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

extract_humble() {
	# Extract and organize game files if the installer exists
	unzip -o Guacamelee_DRMFREE.sh
	if [ -d "data/noarch" ]; then
		mv -f data/noarch/* "$GAMEDIR/gamedata/" || { echo "Failed to move game directory." ; sleep 5; exit 1; }
	else
		echo "Game directory not found after extraction."
		sleep 5
		exit 1
	fi
	if [ -f "data/x86/game-bin" ]; then
		mv -f data/x86/game-bin "$GAMEDIR/gamedata/" || { echo "Failed to move game-bin." ; sleep 5; exit 1; }
		chmod +x "$GAMEDIR/gamedata/game-bin"
	else
		echo "game-bin not found after extraction."
		sleep 5
		exit 1
	fi
	rm -rf data/ meta/ scripts/
	rm -f Guacamelee_DRMFREE.sh
}

extract_gog(){
	# Extract and organize game files if the installer exists
	unzip -o gog_guacamelee_gold_edition_2.0.0.3.sh
	if [ -d "data/noarch/game" ]; then
		mv -f data/noarch/game/* "$GAMEDIR/gamedata/" || { echo "Failed to move game directory." ; sleep 5; exit 1; }
	else
		echo "Game directory not found after extraction."
		sleep 5
		exit 1
	fi
	rm -rf data/ meta/ scripts/
	rm -f gog_guacamelee_gold_edition_2.0.0.3.sh
}

# call extract function

if [ -f "Guacamelee_DRMFREE.sh" ]; then
	extract_humble
elif [ -f "gog_guacamelee_gold_edition_2.0.0.3.sh" ]; then
	extract_gog
else
	echo "Game installation file is missing"
	exit 1
fi

echo "Setup complete. Have fun playing!"
