#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="dark_deity.port"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

unzip_assets() {
    # Unzip assets from the located .exe file into $DATADIR
    echo "Unzipping assets from $EXE_FILE..."
    ./tools/7za x "$EXE_FILE" -o"$DATADIR" -y
    
    if [ $? -eq 0 ]; then
        echo "Assets unzipped successfully to $DATADIR."
        rm -f "$EXE_FILE"
    else
        echo "Failed to unzip assets."
        exit 1
    fi
}

unzip_patch() {
    echo "Unzipping the patch file..."
    if [ -f "./tools/patches/darkdeity.zip.001" ]; then
        if [ -x "$(command -v 7z)" ]; then
            ./tools/7za x ./tools/patches/darkdeity.zip.001 -o./tools/patches
            if [ $? -eq 0 ]; then
                echo "Patch file successfully extracted."
                rm ./tools/patches/darkdeity.zip.*
            else
                echo "Failed to extract multi-part archive."
                exit 1
            fi
        else
            echo "7za tool is not available. Failed to extract xdelta patch."
            exit 1
        fi
    else
        echo "Patch archive not found!"
        exit 1
    fi
}
apply_xdelta() {
    # Check if both data.win and darkdeity.xdelta files exist before applying the patch
    if [ -f "$DATADIR/data.win" ]; then
        if [ -f "./tools/patches/darkdeity.xdelta" ]; then
            output=$(xdelta3 -d -s "$DATADIR/data.win" -f "./tools/patches/darkdeity.xdelta" "$DATADIR/game.droid" 2>&1)
            if [ $? -eq 0 ]; then
                echo "Patch applied successfully"
                echo "$output"
                rm "$DATADIR/data.win"
            else
                echo "Failed to apply patch"
                echo "$output"
                exit 1
            fi
        else
            echo "No .xdelta file found; skipping patching."
        fi
    else
        echo "No data.win file found to patch!"
    fi
}

compress_audio() {
    mkdir -p "$TMPDIR"

    # Run the compression tool
    PYTHON=$(which python3)
    echo "Running GMTools on data and audiogroups."
    $PYTHON ./tools/gmKtool.py -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$DATADIR"
        echo "Moved compressed files to $DATADIR."
        rmdir "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
    else
        echo "Audio compression failed."
        echo "Cleaning up temporary directory $TMPDIR."
        rm -rf "$TMPDIR"
    fi
}

zip_archive() {
        mv $DATADIR/splash.png .
        zip -r -0 $DATAFILE ./assets/
        echo "Zipped contents to $DATAFILE"
        rm -rf ./assets
}

process_game() { 
    # Delete the files we don't need and retrieve the splash, move other files to saves folder
    echo "Moving files around..."
    rm -rf $DATADIR/*.dll $DATADIR/.gitkeep $DATADIR/*.exe
    mkdir -p saves
    [ -d "$DATADIR/Bonds" ] && mv "$DATADIR/Bonds" ./saves/Bonds
    [ -d "$DATADIR/Scenes" ] && mv "$DATADIR/Scenes" ./saves/Scenes
    [ -d "$DATADIR/Stories" ] && mv "$DATADIR/Stories" ./saves/Stories
    
    sleep 1
    echo "Unpacking xdelta patch..."
    unzip_patch
    sleep 1
    echo "Applying xdelta patch..."
    apply_xdelta
    sleep 1
    echo "Compressing audio..."
    compress_audio
    sleep 1
    echo "Finishing up..."
    zip_archive
    sleep 1
	
    # Final completion message
    echo "Patching process complete!"
}

# Call the function
process_game