rgssVersion=3

fullscreen=true
winResizable=false
anyAltToggleFS=true
smoothScaling=true
vsync=true
subImageFix=true
enableBlitting=false
frameSkip=false
fixedAspectRatio=true

defScreenW=544
defScreenH=416

gameFolder=./

preloadScript=my_win32_wrapper.rb

fontSub=Arial>Open Sans
fontSub=Times New Roman>Open Sans
