#!/bin/bash

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt
export PORT_32BIT="Y"
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
get_controls

GAMEDIR="/$directory/ports/Uber/gamedata/omega"

export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/../lib:$GAMEDIR/libs:$LD_LIBRARY_PATH"
export GMLOADER_DEPTH_DISABLE=1
export GMLOADER_SAVEDIR="$GAMEDIR/gamedata/"

if [[ "$DEVICE_RAM" -lt 2 ]]; then
   if [[ "${CFW_NAME^^}" == *"ARKOS"* ]] || [[ "${CFW_NAME^^}" == *"ODROID"* ]]; then
       pm_message "Preparing Swap File, please wait..."
       [ -f /swapfile ] && $ESUDO swapoff -v /swapfile
       [ -f /swapfile ] && $ESUDO rm -f /swapfile
       $ESUDO fallocate -l 384M /swapfile
       $ESUDO chmod 600 /swapfile
       $ESUDO mkswap /swapfile
       $ESUDO swapon /swapfile
       [ -f $GAMEDIR/timidity.cfg ] && $ESUDO rm -f $GAMEDIR/timidity.cfg
   elif [[ "${CFW_NAME^^}" == "KNULLI" ]]; then
       pm_message "Preparing Swap File, please wait..."
       [ -f /media/SHARE/swapfile ] && $ESUDO swapoff -v /media/SHARE/swapfile
       [ -f /media/SHARE/swapfile ] && $ESUDO rm -f /media/SHARE/swapfile
       $ESUDO fallocate -l 384M /media/SHARE/swapfile
       $ESUDO chmod 600 /media/SHARE/swapfile
       $ESUDO mkswap /media/SHARE/swapfile
       $ESUDO swapon /media/SHARE/swapfile
       [ -f $GAMEDIR/timidity.cfg ] && $ESUDO rm -f $GAMEDIR/timidity.cfg
   fi
fi

cd "$GAMEDIR"

> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1

[ -f "./gamedata/data.win" ] && mv gamedata/data.win gamedata/game.droid
[ -f "./gamedata/game.win" ] && mv gamedata/game.win gamedata/game.droid

find gamedata -type f \( -iname "*.dll" -o -iname "*.exe" \) -delete

$GPTOKEYB "gmloader" -c "$GAMEDIR/omega.gptk" &
pm_message "Loading, please wait... " > /dev/tty0

$ESUDO chmod +x "$GAMEDIR/gmloader"
pm_platform_helper "$GAMEDIR/gmloader"
./gmloader omega.port

pm_finish
