#!/bin/bash

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt
export PORT_32BIT="Y"
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
get_controls

GAMEDIR="/$directory/ports/Uber/gamedata/ubermosh"

export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/../lib:$GAMEDIR/libs:$LD_LIBRARY_PATH"
export GMLOADER_DEPTH_DISABLE=1
export GMLOADER_SAVEDIR="$GAMEDIR/gamedata/"

if [[ $DEVICE_RAM -lt "2" ]]; then
  if [[ $CFW_NAME == *"ArkOS"* ]] || [[ $CFW_NAME == *"ODROID"* ]]; then
    if [[ $CFW_NAME == *"dArkOS"* ]]; then
      [ -e /dev/zram0 ] && $ESUDO swapoff -a
      [ -e /dev/zram0 ] && $ESUDO zramctl --reset /dev/zram0
      [ -e /dev/zram1 ] && $ESUDO zramctl --reset /dev/zram1
      [ -e /dev/zram2 ] && $ESUDO zramctl --reset /dev/zram2
      modprobe zram
      $ESUDO zramctl --find --size 420M
      $ESUDO mkswap /dev/zram0
      $ESUDO swapon /dev/zram0
    else
      [ -f /swapfile ] && $ESUDO swapoff -v /swapfile
      [ -f /swapfile ] && $ESUDO rm -f /swapfile
      $ESUDO fallocate -l 420M /swapfile
      $ESUDO chmod 600 /swapfile
      $ESUDO mkswap /swapfile
      $ESUDO swapon /swapfile
    fi
  elif [[ "${CFW_NAME^^}" == "KNULLI" ]]; then
    if [ ! -e /dev/zram0 ]; then
        pm_message "For Knulli, you must enable ZRAM.  Start -> System Settings -> Services -> ZRAMSWAP"
        sleep 7
    fi
  fi
fi

cd "$GAMEDIR"

> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1

[ -f "./gamedata/data.win" ] && mv gamedata/data.win gamedata/game.droid
[ -f "./gamedata/game.win" ] && mv gamedata/game.win gamedata/game.droid

find gamedata -type f \( -iname "*.dll" -o -iname "*.exe" \) -delete

$GPTOKEYB "gmloader" &

$ESUDO chmod +x "$GAMEDIR/gmloader"
pm_platform_helper "$GAMEDIR/gmloader"
./gmloader ubermosh.port

pm_finish
