#!/bin/bash

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"
LOGERR="$GAMEDIR/patch_error.txt"

> "$GAMEDIR/patchlog.txt" && exec > >(tee "$GAMEDIR/patchlog.txt") 2>&1

# extract, diff
GAMEFILE="./gamedata/GravityCircuit.exe"
# unpack the game
"$controlfolder/7zzs.$DEVICE_ARCH" x "$GAMEFILE" -o"./gamedata"
rm "$GAMEFILE"
rm -Rf ./gamedata/platform
cd ./gamedata
# ungh, mixed line ends, there's probably a better way
grep -E '^\+\+\+ ' "../gravitycircuit.diff" | sed -E 's/^\+\+\+ ([^\/]+\/)?//' | cut -f1 | xargs -I {} dos2unix "{}"
# patch the unpacked game
$GAMEDIR/bin.${DEVICE_ARCH}/patch -p1 < "$GAMEDIR/gravitycircuit.diff"

