# Machismo configuration for RatcheteerDX
#
# Paths are relative to CWD (set by launch script to the port directory).

[general]
dylib_map = conf/dylib_map.conf

[trampoline.sdl2_image]
lib = libSDL2_image-2.0.so.0
prefix = _IMG_

[trampoline.sdl2]
lib = libSDL2-2.0.so.0
prefix = _SDL_

[trampoline.steam_noop]
lib = STUB
prefix = __ZN3wos5steam
prefix = __ZNK3wos5steam
