#!/bin/sh

ORIGINAL="/usr/bin/batocera-audio"
BACKUP="/tmp/batocera-audio-original.sh"
WRAPPER="/tmp/batocera-audio-wrapper.sh"

if [ ! -f "$BACKUP" ]; then
  echo "Backing up original script..."
  cp "$ORIGINAL" "$BACKUP"
else
  echo "Backup already exists"
fi

echo "Creating wrapper script..."
cat > "$WRAPPER" << 'EOF'
#!/bin/sh

# Call original script, with all params
/tmp/batocera-audio-original.sh "$@"

# If call is for setSystemVolume, send new volume to tcp
if [ "$1" = "setSystemVolume" ]; then
	# Send new vol value to Godot
	HOST="127.0.0.1"
	PORT="23456"

	VAL=$(/tmp/batocera-audio-original.sh getSystemVolume 2>/dev/null | tr -d '\n\r')

	echo "$VAL" | nc "$HOST" "$PORT" 2>/dev/null &
fi
EOF

chmod +x "$WRAPPER"


# Avoid double mount
if findmnt -n "$ORIGINAL" >/dev/null 2>&1; then
  echo "Already bind-mounted, skipping"
  exit 0
fi

echo "Bind-mounting wrapper over original..."
mount --bind "$WRAPPER" "$ORIGINAL"
