#!/bin/sh

ORIGINAL="/usr/bin/batocera-audio"
BACKUP="/tmp/batocera-audio-original.sh"
WRAPPER="/tmp/batocera-audio-wrapper.sh"

umount -l "$ORIGINAL"

# Remove temp files
if [ -f "$WRAPPER" ]; then
    rm -f "$WRAPPER"
fi

if [ -f "$BACKUP" ]; then
    rm -f "$BACKUP"
fi
