#!/bin/bash

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt
[[ "${CFW_NAME^^}" == 'MUOS' ]] && directory=$(realpath "$0" | sed 's|^\./||' | awk -F'/' '{print "/" $2 "/" $3}')
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
get_controls

GAMEDIR="/$directory/ports/tileworld"

> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1

[ ! -f "$GAMEDIR/port_cfg" ] && cp -f "$GAMEDIR/port_cfg.template" "$GAMEDIR/port_cfg"
$ESUDO chmod 777 -R $GAMEDIR/*

export DEVICE_ARCH="${DEVICE_ARCH:-aarch64}"
export LD_LIBRARY_PATH="$GAMEDIR/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

cd $GAMEDIR

bind_directories ~/.tworld $GAMEDIR/conf/.tworld

cp -f -v $GAMEDIR/libs.${DEVICE_ARCH}/sdl12-compat.default $GAMEDIR/libs.${DEVICE_ARCH}/libSDL-1.2.so.0

# set game mod
cp -f -v $GAMEDIR/res/rc.hh.original $GAMEDIR/res/rc
cp -f -v $GAMEDIR/res/atiles_ms.png $GAMEDIR/res/atiles.png

$GPTOKEYB "tworld-hh.${DEVICE_ARCH}" -c "$GAMEDIR/tileworld.gptk" &
pm_platform_helper "$GAMEDIR/tworld-hh.${DEVICE_ARCH}"
./tworld-hh.${DEVICE_ARCH} -F

pm_finish
