#!/bin/sh
cat guitar.txt | while read chord first third fifth
do
  echo "$chord"
  sox -n -r 16000 -b 16 "chord-${chord}.wav" \
    synth pl "$first" pl "$third" pl "$fifth" \
    delay 0 .05 .1 remix - fade 0 1 .095 norm -1
done
