#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="patchlog.txt"
LOGERR="patcherr.txt"

# Redirect output and error to the log file
> "$GAMEDIR/$LOGFILE" && exec > >(tee "$GAMEDIR/$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Patch failure function
patch_failure() {
    $ESUDO umount "$TOOLKIT" 2>/dev/null || true
    # Exit script, or return if sourced
    return 1 2>/dev/null || exit 1
}

# Mount the GMToolkit runtime
TOOLKIT="$HOME/gmtoolkit"
RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
if [ -f "$RUNTIME" ]; then
    $ESUDO mkdir -p "$TOOLKIT"
    $ESUDO umount "$TOOLKIT" 2>/dev/null || true
    $ESUDO mount "$RUNTIME" "$TOOLKIT"
else
    echo "This port requires the GMToolkit runtime. Please download it."
    sleep 2
    patch_failure
fi

# Exports
export PATH="$TOOLKIT/gmtools:$PATH"
export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export DATADIR="$GAMEDIR/assets"
export TOOLDIR="$GAMEDIR/tools"
export DATAFILE="iosas.port"
export TMPDIR="$GAMEDIR/tmp"

# Permissions
chmod 666 /dev/uinput

cd "$GAMEDIR"

# Set up trap for cleaning TMPDIR on exit
trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0

# Attempt to get SAVEDIR from gmloader.json using jq
if command -v jq >/dev/null 2>&1; then
    SAVEDIR=$(jq -r '.save_dir // empty' "$GAMEDIR/gmloader.json" 2>/dev/null)
else
    SAVEDIR="$GAMEDIR/saves"
fi

# Test for commands: python, zip
PYTHON=$(command -v python3)
if [ -z "$PYTHON" ]; then
    echo "Missing Python!"
    patch_failure
fi

ZIP=$(command -v zip)
if [ -z "$ZIP" ]; then
    echo "Missing zip!"
    patch_failure
fi

prepare_files() {
	# Apply the patch
		echo "Applying a patch"
		checksum=$(md5sum "assets/data.win" | awk '{ print $1 }')
		# Check for Itch.io version
		if [ "$checksum" == "65e168afb8093a441541ec57e98b30ec" ]; then
			$controlfolder/xdelta3 -d -s "$GAMEDIR/assets/data.win" -f "$TOOLDIR/patchitch.xdelta" "$GAMEDIR/assets/game.droid" 2>&1
			echo "Patch for the Itch.io version has been applied"
		# Check for Steam version
		elif [ "$checksum" == "8d0bb55a6b975ccc054acd06bcf1f757" ]; then
			$controlfolder/xdelta3 -d -s "$GAMEDIR/assets/data.win" -f "$TOOLDIR/patchsteam.xdelta" "$GAMEDIR/assets/game.droid" 2>&1
			echo "Patch for the Steam version has been applied"
		else
			echo "Failed to apply a patch"
	fi	

}

cpu_check() {
    
    CONFIG="$SAVEDIR/config.ini"

    # Check for pm-config.ini, rename if found
    if [ -f "$SAVEDIR/pm-config.ini" ]; then
        mv "$SAVEDIR/pm-config.ini" "$CONFIG"
        echo "Renamed old config ini file to match new version."
    fi
    
    # Check for config.ini, log if not found
    if [ ! -f "$CONFIG" ]; then
        echo "Error: Configuration file ($CONFIG) not found!"
        return 1
    fi

    case "$DEVICE_CPU" in
        # CPUs with less than 1.5 GHz
        "a133plus"|"h700"|"RK3326")
            # Set frameskip and turn IdolSFX off for CPUs with less than 1.5 GHz
            if ! sed -i 's/^FrameSkip=[0-9]\+$/FrameSkip=20/' "$CONFIG"; then
                echo "Error: Failed to update FrameSkip in $CONFIG"
            fi
            if ! sed -i 's/^IdolSFX=[0-9]\+$/IdolSFX=0/' "$CONFIG"; then
                echo "Error: Failed to update IdolSFX in $CONFIG"
            fi
            ;;
        
        # CPUs with 2 GHz or more
        "SD865"|"RK3388"|"RK3566"|"RK3399"|"S922X"|"x86_64")
            # Set frameskip to 0 (no frameskip) and leave IdolSFX on for CPUs with 2 GHz or more
            if ! sed -i 's/^FrameSkip=[0-9]\+$/FrameSkip=0/' "$CONFIG"; then
                echo "Error: Failed to update FrameSkip in $CONFIG"
            fi
            if ! sed -i 's/^IdolSFX=[0-9]\+$/IdolSFX=1/' "$CONFIG"; then
                echo "Error: Failed to update IdolSFX in $CONFIG"
            fi
            ;;
        
        *)
            # Default case: set frameskip and turn IdolSFX off for other CPUs
            if ! sed -i 's/^FrameSkip=[0-9]\+$/FrameSkip=20/' "$CONFIG"; then
                echo "Error: Failed to update FrameSkip in $CONFIG"
            fi
            if ! sed -i 's/^IdolSFX=[0-9]\+$/IdolSFX=0/' "$CONFIG"; then
                echo "Error: Failed to update IdolSFX in $CONFIG"
            fi
            ;;
    esac
}

compress_audio() {
    
    # Do audio compression
    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
        mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
        echo "Audio compression applied successfully."
    else
        # Failure
        echo "Audio compression failed for $GAMEFILE."
        rmdir "$TMPDIR"
        return 1
    fi
}

zip_archive() {
	# Delete unnecessary files
	rm -f assets/*.{exe,dll,win}
	zip -r -0 $DATAFILE ./assets/
	rm -rf $DATADIR/*
}


process_game() {
    cpu_check
    prepare_files|| { patch_failure; return 1; }
    sleep 1
    echo "Compressing audio..."
    compress_audio || { patch_failure; return 1; }
    sleep 1
    echo "Finishing up..."
    zip_archive || { patch_failure; return 1; }
}


# Call the function
if ! process_game; then
    echo "Patching process failed!"
    mv "$LOGFILE" "$LOGERR"
else
    echo "Patching process complete!"
fi

# Unmount runtimes
$ESUDO umount "$TOOLKIT" 2>/dev/null || true

