#!/bin/bash

#
#   Dust: and Elysian Tale 
#   Author: JanTrueno
#   Version: 1.0
#

# Set GAMEDIR to the current directory and set logfile
export GAMEDIR="$PWD"
export ASTC_QUALITY=30.0
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# ----------------- BEGIN PATCH -----------------

# Remove Fonts if it's a broken symlink or not a directory
if [ -e "$GAMEDIR/gamedata/Content/Fonts" ] && [ ! -d "$GAMEDIR/gamedata/Content/Fonts" ]; then
    echo "Removing non-directory or broken Fonts file..."
    rm -f "$GAMEDIR/gamedata/Content/Fonts"
fi

# Backup original fonts if not already done
if [ -d "$GAMEDIR/gamedata/Content/Fonts-orig" ] && [ ! -d "$GAMEDIR/gamedata/Content/Fonts" ]; then
    echo "Copying Fonts-orig to Fonts..."
    cp -r "$GAMEDIR/gamedata/Content/Fonts-orig" "$GAMEDIR/gamedata/Content/Fonts"
fi

# Apply repacking process using FNARepacker
mono "${GAMEDIR}/tools/FNARepacker.exe" "${GAMEDIR}/gamedata/Content/gfx"

