#!/bin/sh

ORIGINAL="/opt/muos/script/device/audio.sh"
BACKUP="/tmp/muos_audio_original.sh"
WRAPPER="/tmp/muos_audio_wrapper.sh"

umount -l "$ORIGINAL"

# Remove temp files
if [ -f "$WRAPPER" ]; then
    rm -f "$WRAPPER"
fi

if [ -f "$BACKUP" ]; then
    rm -f "$BACKUP"
fi