#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/gamedata"
export LD_LIBRARY_PATH="$GAMEDIR/tools/libs.aarch64:$LD_LIBRARY_PATH"
export TOOLDIR="$GAMEDIR/tools"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/innoextract"

EXE=$(find "$DATADIR" -maxdepth 1 -name "setup*.exe")
"$TOOLDIR/innoextract" -e -d "$DATADIR" $EXE
mv "$DATADIR"/app/* "$DATADIR/"
rm -rf "$DATADIR/tmp"

# Delete unneeded files from DATADIR
rm -r $DATADIR/__redist $DATADIR/*.exe $DATADIR/*.dll
rm -r $DATADIR/*.tmp $DATADIR/*.bat $DATADIR/goggame* $DATADIR/*.ico

# Delete installer
#rm "$DATADIR"/setup*.exe "$DATADIR"/setup*.bin
