#!/bin/bash

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

EXTRACT_DIR="$GAMEDIR/extract"
python3 "$GAMEDIR/tools/gogextract.py" \
  "$GAMEDIR/gamedata/"gog_la_mulana_*.sh "$EXTRACT_DIR"
unzip "$GAMEDIR/extract/data.zip" -d "$EXTRACT_DIR"
mv "$EXTRACT_DIR/data/noarch/game" "$GAMEDIR"

rm -r "$GAMEDIR/extract"

if [ -f "$GAMEDIR/game/$BINARY" ]; then
  # success, delete setup file
  rm -r "$GAMEDIR"/gamedata/*.sh
fi
