#!/bin/bash

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
TMPDIR="$GAMEDIR/tmp"
DATADIR="$GAMEDIR/gamedata"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

mkdir "$TMPDIR"

cd "$DATADIR"
python3 "$GAMEDIR/tools/gogextract.py" \
  ./gog_la_mulana_*.sh "$TMPDIR"
unzip "$TMPDIR/data.zip" -d "$TMPDIR"
mv "$TMPDIR"/data/noarch/game/* "$DATADIR"

rm -r "$TMPDIR"

if [ -f "$DATADIR/$BINARY" ]; then
  # success, delete setup file
  rm -r "$DATADIR"/*.sh
fi
