#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"
LOGERR="$GAMEDIR/patch_error.txt"

# Redirect output and error to the log file
rm -rf $LOGFILE $LOGERR
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="dokimon.port"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

cd "$GAMEDIR"

remove_files() {
    # Delete unnecessary files
    rm -rf $DATADIR/*.exe $DATADIR/*.dll $DATADIR/.gitkeep \
           $DATADIR/GMLive
    echo "Removed unnecessary files"
    if [ -f "$DATADIR/data.win" ]; then
        mv "$DATADIR/data.win" "$DATADIR/game.droid"
    fi
    sleep 1
}

zip_archive() {
        echo "Finishing up..."
        touch $DATADIR/config.ini
        zip -r -0 $DATAFILE ./assets/
        mkdir -p saves
        rm -rf $DATADIR/*
        sleep 1
}

remove_demo() {
    # Change gmloader.json to new .port file
    sed -i "s/\"apk_path\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"apk_path\": \"$DATAFILE\"/" gmloader.json
    rm -rf "$GAMEDIR/dokimondemo.port"
}

process_game() {
    remove_files
    zip_archive
    remove_demo
	
    # Final completion message
    echo "Patching process complete!"
}

process_game
