local modpath = minetest.get_modpath(minetest.get_current_modname())

dofile(modpath.."/mcl_trees.lua")
dofile(modpath.."/mcl_doors.lua")
dofile(modpath.."/mcl_tools.lua")
dofile(modpath.."/mcl_dyes.lua")
dofile(modpath.."/mcl_copper.lua")
dofile(modpath.."/mcl_stairs.lua")
dofile(modpath.."/mcl_crimson.lua")
dofile(modpath.."/mcl_armor.lua")
dofile(modpath.."/mcl_panes.lua")
dofile(modpath.."/mesecons.lua")
