minetest.register_alias("mcl_core:birchtree","mcl_trees:tree_birch")
minetest.register_alias("mcl_core:darktree","mcl_trees:tree_dark_oak")
minetest.register_alias("mcl_core:acaciatree","mcl_trees:tree_acacia")
minetest.register_alias("mcl_core:jungletree","mcl_trees:tree_jungle")
minetest.register_alias("mcl_core:sprucetree","mcl_trees:tree_spruce")
minetest.register_alias("mcl_core:tree","mcl_trees:tree_oak")
minetest.register_alias("default:tree","mcl_trees:tree_oak")
minetest.register_alias("mcl_mangrove:mangrove_tree","mcl_trees:tree_mangrove")
minetest.register_alias("mcl_crimson:crimson_hyphae","mcl_trees:tree_crimson")
minetest.register_alias("mcl_crimson:warped_hyphae","mcl_trees:tree_warped")
minetest.register_alias("mcl_bamboo:bamboo_block","mcl_trees:tree_bamboo")
minetest.register_alias("mcl_cherry_blossom:cherrytree","mcl_trees:tree_cherry_blossom")

minetest.register_alias("mcl_core:birchleaves","mcl_trees:leaves_birch")
minetest.register_alias("mcl_core:darkleaves","mcl_trees:leaves_dark_oak")
minetest.register_alias("mcl_core:acacialeaves","mcl_trees:leaves_acacia")
minetest.register_alias("mcl_core:jungleleaves","mcl_trees:leaves_jungle")
minetest.register_alias("mcl_core:spruceleaves","mcl_trees:leaves_spruce")
minetest.register_alias("mcl_core:leaves","mcl_trees:leaves_oak")
minetest.register_alias("default:leaves","mcl_trees:leaves_oak")
minetest.register_alias("mcl_mangrove:mangroveleaves","mcl_trees:leaves_mangrove")
minetest.register_alias("mcl_cherry_blossom:cherryleaves","mcl_trees:leaves_cherry_blossom")
minetest.register_alias("default:acacia_tree", "mcl_core:acaciatree")
minetest.register_alias("default:acacia_leaves", "mcl_core:acacialeaves")

minetest.register_alias("mcl_core:birchleaves_orphan","mcl_trees:leaves_birch_orphan")
minetest.register_alias("mcl_core:darkleaves_orphan","mcl_trees:leaves_dark_oak_orphan")
minetest.register_alias("mcl_core:acacialeaves_orphan","mcl_trees:leaves_acacia_orphan")
minetest.register_alias("mcl_core:jungleleaves_orphan","mcl_trees:leaves_jungle_orphan")
minetest.register_alias("mcl_core:spruceleaves_orphan","mcl_trees:leaves_spruce_orphan")
minetest.register_alias("mcl_core:leaves_orphan","mcl_trees:leaves_oak_orphan")
minetest.register_alias("mcl_mangrove:mangroveleaves_orphan","mcl_trees:leaves_mangrove_orphan")

minetest.register_alias("mcl_core:birchwood","mcl_trees:wood_birch")
minetest.register_alias("mcl_core:big_oakwood","mcl_trees:wood_dark_oak")
minetest.register_alias("mcl_core:darkwood","mcl_trees:wood_dark_oak")
minetest.register_alias("mcl_core:acaciawood","mcl_trees:wood_acacia")
minetest.register_alias("mcl_core:junglewood","mcl_trees:wood_jungle")
minetest.register_alias("mcl_core:sprucewood","mcl_trees:wood_spruce")
minetest.register_alias("mcl_core:wood","mcl_trees:wood_oak")
minetest.register_alias("mcl_crimson:warped_hyphae_wood","mcl_trees:wood_warped")
minetest.register_alias("mcl_crimson:crimson_hyphae_wood","mcl_trees:wood_crimson")
minetest.register_alias("mcl_mangrove:mangrove_wood","mcl_trees:wood_mangrove")
minetest.register_alias("default:wood","mcl_trees:wood_oak")
minetest.register_alias("mcl_bamboo:bamboo_plank","mcl_trees:wood_bamboo")
minetest.register_alias("mcl_cherry_blossom:cherrywood","mcl_trees:wood_cherry_blossom")

minetest.register_alias("mcl_core:birchtree_bark","mcl_trees:bark_birch")
minetest.register_alias("mcl_core:big_oaktree_bark","mcl_trees:bark_dark_oak")
minetest.register_alias("mcl_core:darktree_bark","mcl_trees:bark_dark_oak")
minetest.register_alias("mcl_core:acaciatree_bark","mcl_trees:bark_acacia")
minetest.register_alias("mcl_core:jungletree_bark","mcl_trees:bark_jungle")
minetest.register_alias("mcl_core:sprucetree_bark","mcl_trees:bark_spruce")
minetest.register_alias("mcl_core:tree_bark","mcl_trees:bark_oak")
minetest.register_alias("mcl_crimson:warped_hyphae_bark","mcl_trees:bark_warped")
minetest.register_alias("mcl_crimson:crimson_hyphae_bark","mcl_trees:bark_crimson")
minetest.register_alias("mcl_mangrove:mangrove_tree_bark","mcl_trees:bark_mangrove")
minetest.register_alias("mcl_cherry_blossom:cherrytree_bark","mcl_trees:bark_cherry_blossom")

minetest.register_alias("mcl_core:birchsapling","mcl_trees:sapling_birch")
minetest.register_alias("mcl_core:big_oaksapling","mcl_trees:sapling_dark_oak")
minetest.register_alias("mcl_core:darksapling","mcl_trees:sapling_dark_oak")
minetest.register_alias("mcl_core:acaciasapling","mcl_trees:sapling_acacia")
minetest.register_alias("mcl_core:junglesapling","mcl_trees:sapling_jungle")
minetest.register_alias("mcl_core:sprucesapling","mcl_trees:sapling_spruce")
minetest.register_alias("mcl_core:sapling","mcl_trees:sapling_oak")
minetest.register_alias("default:sapling","mcl_trees:sapling_oak")
minetest.register_alias("mcl_cherry_blossom:cherrysapling","mcl_trees:sapling_cherry_blossom")

minetest.register_alias("mcl_flowerpots:flower_pot_birchsapling","mcl_flowerpots:flower_pot_sapling_birch")
minetest.register_alias("mcl_flowerpots:flower_pot_big_oaksapling","mcl_flowerpots:flower_pot_sapling_dark_oak")
minetest.register_alias("mcl_flowerpots:flower_pot_darksapling","mcl_flowerpots:flower_pot_sapling_dark_oak")
minetest.register_alias("mcl_flowerpots:flower_pot_acaciasapling","mcl_flowerpots:flower_pot_sapling_acacia")
minetest.register_alias("mcl_flowerpots:flower_pot_junglesapling","mcl_flowerpots:flower_pot_sapling_jungle")
minetest.register_alias("mcl_flowerpots:flower_pot_sprucesapling","mcl_flowerpots:flower_pot_sapling_spruce")
minetest.register_alias("mcl_flowerpots:flower_pot_sapling","mcl_flowerpots:flower_pot_sapling_oak")
minetest.register_alias("mcl_flowerpots:flower_pot_bamboo_plant","mcl_flowerpots:flower_pot_bamboo")

minetest.register_alias("mcl_fences:fence","mcl_fences:oak_fence")
minetest.register_alias("mcl_mangrove:mangrove_wood_fence","mcl_fences:mangrove_fence")
minetest.register_alias("mcl_crimson:crimson_fence","mcl_fences:crimson_fence")
minetest.register_alias("mcl_crimson:warped_fence","mcl_fences:warped_fence")
minetest.register_alias("mcl_cherry_blossom:cherry_fence","mcl_fences:cherry_blossom_fence")
minetest.register_alias("mcl_bamboo:bamboo_fence","mcl_fences:bamboo_fence")

minetest.register_alias("mcl_fences:fence_gate","mcl_fences:oak_fence_gate")
minetest.register_alias("mcl_mangrove:mangrove_wood_fence_gate","mcl_fences:mangrove_fence_gate")
minetest.register_alias("mcl_crimson:crimson_fence_gate","mcl_fences:crimson_fence_gate")
minetest.register_alias("mcl_crimson:warped_fence_gate","mcl_fences:warped_fence_gate")

minetest.register_alias("mcl_fences:fence_gate_open","mcl_fences:oak_fence_gate_open")
minetest.register_alias("mcl_cherry_blossom:cherry_fence_gate","mcl_fences:cherry_blossom_fence_gate")
minetest.register_alias("mcl_bamboo:bamboo_fence_gate","mcl_fences:bamboo_fence_gate")

minetest.register_alias("mclx_fences:nether_brick_fence_gate","mcl_fences:nether_brick_fence_gate")
minetest.register_alias("mclx_fences:red_nether_brick_fence_gate","mcl_fences:red_nether_brick_fence_gate")

minetest.register_alias("mclx_fences:nether_brick_fence_gate_open","mcl_fences:nether_brick_fence_gate_open")
minetest.register_alias("mclx_fences:red_nether_brick_fence_gate_open","mcl_fences:red_nether_brick_fence_gate_open")

minetest.register_alias("mclx_fences:nether_brick_fence","mcl_fences:nether_brick_fence")
minetest.register_alias("mclx_fences:red_nether_brick_fence","mcl_fences:red_nether_brick_fence")

minetest.register_alias("mcl_mangrove:mangrove_wood_fence_gate_open","mcl_fences:mangrove_fence_gate_open")
minetest.register_alias("mcl_crimson:warped_fence_gate_open","mcl_fences:warped_fence_gate_open")
minetest.register_alias("mcl_crimson:crimson_fence_gate_open","mcl_fences:crimson_fence_gate_open")
minetest.register_alias("mcl_bamboo:bamboo_fence_gate_open","mcl_fences:bamboo_fence_gate_open")
minetest.register_alias("mcl_cherry_blossom:cherry_fence_gate_open","mcl_fences:cherry_blossom_fence_gate_open")

local function door_alias(oldmod,oldwood,newwood)
	newwood = newwood or oldwood
	minetest.register_alias(oldmod..":"..oldwood.."_door", "mcl_doors:door_"..newwood)
	minetest.register_alias(oldmod..":"..oldwood.."_door_b_1", "mcl_doors:door_"..newwood.."_b_1")
	minetest.register_alias(oldmod..":"..oldwood.."_door_t_1", "mcl_doors:door_"..newwood.."_t_1")
	minetest.register_alias(oldmod..":"..oldwood.."_door_b_2", "mcl_doors:door_"..newwood.."_b_2")
	minetest.register_alias(oldmod..":"..oldwood.."_door_t_2", "mcl_doors:door_"..newwood.."_t_2")

	--alias mcl2's strange _3 and _4 doors
	minetest.register_alias(oldmod..":"..oldwood.."_door_b_3", "mcl_doors:door_"..newwood.."_b_1")
	minetest.register_alias(oldmod..":"..oldwood.."_door_t_3", "mcl_doors:door_"..newwood.."_t_1")
	minetest.register_alias(oldmod..":"..oldwood.."_door_b_4", "mcl_doors:door_"..newwood.."_b_2")
	minetest.register_alias(oldmod..":"..oldwood.."_door_t_4", "mcl_doors:door_"..newwood.."_t_2")
end

door_alias("mcl_doors","wooden","oak")
door_alias("mcl_doors","jungle")
door_alias("mcl_doors","acacia")
door_alias("mcl_doors","dark_oak")
door_alias("mcl_doors","spruce")
door_alias("mcl_doors","birch")
door_alias("mcl_mangrove","mangrove")
door_alias("mcl_crimson","warped")
door_alias("mcl_crimson","crimson")
door_alias("mcl_bamboo","bamboo")
door_alias("mcl_cherry_blossom","cherry","cherry_blossom")

minetest.register_alias("mcl_doors:dark_door","mcl_doors:door_dark_oak") -- realy?

minetest.register_alias("mcl_doors:iron_door_b_3","mcl_doors:iron_door_b_1")
minetest.register_alias("mcl_doors:iron_door_t_3","mcl_doors:iron_door_t_1")
minetest.register_alias("mcl_doors:iron_door_b_4","mcl_doors:iron_door_b_2")
minetest.register_alias("mcl_doors:iron_door_t_4","mcl_doors:iron_door_t_2")

local function trapdoor_alias(oldmod,oldwood, newwood)
	local oldwood_ = (oldwood == "") and "" or oldwood.."_"
	newwood = (oldwood == "") and "oak" or newwood or oldwood
	minetest.register_alias(oldmod..":"..oldwood_.."trapdoor","mcl_doors:trapdoor_"..newwood)
	minetest.register_alias(oldmod..":"..oldwood_.."trapdoor_open","mcl_doors:trapdoor_"..newwood.."_open")
	minetest.register_alias(oldmod..":"..oldwood_.."trapdoor_ladder","mcl_doors:trapdoor_"..newwood.."_open")
end

trapdoor_alias("mcl_doors","")
trapdoor_alias("mcl_doors","spruce")
trapdoor_alias("mcl_doors","birch")
trapdoor_alias("mcl_doors","acacia")
trapdoor_alias("mcl_doors","jungle")
trapdoor_alias("mcl_doors","dark_oak")
trapdoor_alias("mcl_mangrove","mangrove")
trapdoor_alias("mcl_crimson","warped")
trapdoor_alias("mcl_crimson","crimson")
trapdoor_alias("mcl_bamboo","bamboo")
trapdoor_alias("mcl_cherry_blossom","cherry","cherry_blossom")

minetest.register_alias("mcl_doors:iron_trapdoor_ladder","mcl_doors:iron_trapdoor_open")

minetest.register_alias("mcl_core:stripped_oak","mcl_trees:stripped_oak")
minetest.register_alias("mcl_core:stripped_jungle","mcl_trees:stripped_jungle")
minetest.register_alias("mcl_core:stripped_acacia","mcl_trees:stripped_acacia")
minetest.register_alias("mcl_core:stripped_dark_oak","mcl_trees:stripped_dark_oak")
minetest.register_alias("mcl_core:stripped_spruce","mcl_trees:stripped_spruce")
minetest.register_alias("mcl_core:stripped_birch","mcl_trees:stripped_birch")
minetest.register_alias("mcl_mangrove:mangrove_stripped_trunk","mcl_trees:stripped_mangrove")
minetest.register_alias("mcl_crimson:stripped_warped_hyphae","mcl_trees:stripped_warped")
minetest.register_alias("mcl_crimson:stripped_crimson_hyphae","mcl_trees:stripped_crimson")
minetest.register_alias("mcl_bamboo:bamboo_block_stripped","mcl_trees:stripped_bamboo")
minetest.register_alias("mcl_cherry_blossom:stripped_cherrytree","mcl_trees:stripped_cherry_blossom")

minetest.register_alias("mcl_core:stripped_oak_bark","mcl_trees:bark_stripped_oak")
minetest.register_alias("mcl_core:stripped_jungle_bark","mcl_trees:bark_stripped_jungle")
minetest.register_alias("mcl_core:stripped_acacia_bark","mcl_trees:bark_stripped_acacia")
minetest.register_alias("mcl_core:stripped_dark_oak_bark","mcl_trees:bark_stripped_dark_oak")
minetest.register_alias("mcl_core:stripped_spruce_bark","mcl_trees:bark_stripped_spruce")
minetest.register_alias("mcl_core:stripped_birch_bark","mcl_trees:bark_stripped_birch")
minetest.register_alias("mcl_mangrove:mangrove_stripped_bark","mcl_trees:bark_stripped_mangrove")
minetest.register_alias("mcl_crimson:stripped_warped_hyphae_bark","mcl_trees:bark_stripped_warped")
minetest.register_alias("mcl_crimson:stripped_crimson_hyphae_bark","mcl_trees:bark_stripped_crimson")
minetest.register_alias("mcl_cherry_blossom:stripped_cherrytree_bark","mcl_trees:bark_stripped_cherry_blossom")

minetest.register_alias("mcl_stairs:stair_wood", "mcl_stairs:stair_oak")
minetest.register_alias("mcl_stairs:stair_birchwood", "mcl_stairs:stair_birch")
minetest.register_alias("mcl_stairs:stair_sprucewood", "mcl_stairs:stair_spruce")
minetest.register_alias("mcl_stairs:stair_darkwood", "mcl_stairs:stair_dark_oak")
minetest.register_alias("mcl_stairs:stair_acaciawood", "mcl_stairs:stair_acacia")
minetest.register_alias("mcl_stairs:stair_junglewood", "mcl_stairs:stair_jungle")
minetest.register_alias("mcl_stairs:stair_mangrove_wood", "mcl_stairs:stair_mangrove")
minetest.register_alias("mcl_stairs:stair_crimson_hyphae_wood", "mcl_stairs:stair_crimson")
minetest.register_alias("mcl_stairs:stair_warped_hyphae_wood", "mcl_stairs:stair_warped")
minetest.register_alias("mcl_stairs:stair_bamboo_plank", "mcl_stairs:stair_bamboo")
minetest.register_alias("mcl_stairs:stair_cherrywood", "mcl_stairs:stair_cherry_blossom")

minetest.register_alias("mcl_stairs:stair_wood_inner", "mcl_stairs:stair_oak_inner")
minetest.register_alias("mcl_stairs:stair_birchwood_inner", "mcl_stairs:stair_birch_inner")
minetest.register_alias("mcl_stairs:stair_sprucewood_inner", "mcl_stairs:stair_spruce_inner")
minetest.register_alias("mcl_stairs:stair_darkwood_inner", "mcl_stairs:stair_dark_oak_inner")
minetest.register_alias("mcl_stairs:stair_acaciawood_inner", "mcl_stairs:stair_acacia_inner")
minetest.register_alias("mcl_stairs:stair_junglewood_inner", "mcl_stairs:stair_jungle_inner")
minetest.register_alias("mcl_stairs:stair_mangrove_wood_inner", "mcl_stairs:stair_mangrove_inner")
minetest.register_alias("mcl_stairs:stair_crimson_hyphae_wood_inner", "mcl_stairs:stair_crimson_inner")
minetest.register_alias("mcl_stairs:stair_warped_hyphae_wood_inner", "mcl_stairs:stair_warped_inner")
minetest.register_alias("mcl_stairs:stair_bamboo_plank_inner", "mcl_stairs:stair_bamboo_inner")
minetest.register_alias("mcl_stairs:stair_cherrywood_inner", "mcl_stairs:stair_cherry_blossom_inner")

minetest.register_alias("mcl_stairs:stair_wood_outer", "mcl_stairs:stair_oak_outer")
minetest.register_alias("mcl_stairs:stair_birchwood_outer", "mcl_stairs:stair_birch_outer")
minetest.register_alias("mcl_stairs:stair_sprucewood_outer", "mcl_stairs:stair_spruce_outer")
minetest.register_alias("mcl_stairs:stair_darkwood_outer", "mcl_stairs:stair_dark_oak_outer")
minetest.register_alias("mcl_stairs:stair_acaciawood_outer", "mcl_stairs:stair_acacia_outer")
minetest.register_alias("mcl_stairs:stair_junglewood_outer", "mcl_stairs:stair_jungle_outer")
minetest.register_alias("mcl_stairs:stair_mangrove_wood_outer", "mcl_stairs:stair_mangrove_outer")
minetest.register_alias("mcl_stairs:stair_crimson_hyphae_wood_outer", "mcl_stairs:stair_crimson_outer")
minetest.register_alias("mcl_stairs:stair_warped_hyphae_wood_outer", "mcl_stairs:stair_warped_outer")
minetest.register_alias("mcl_stairs:stair_bamboo_plank_outer", "mcl_stairs:stair_bamboo_outer")
minetest.register_alias("mcl_stairs:stair_cherrywood_outer", "mcl_stairs:stair_cherry_blossom_outer")

minetest.register_alias("mcl_stairs:slab_wood", "mcl_stairs:slab_oak")
minetest.register_alias("mcl_stairs:slab_birchwood", "mcl_stairs:slab_birch")
minetest.register_alias("mcl_stairs:slab_sprucewood", "mcl_stairs:slab_spruce")
minetest.register_alias("mcl_stairs:slab_darkwood", "mcl_stairs:slab_dark_oak")
minetest.register_alias("mcl_stairs:slab_acaciawood", "mcl_stairs:slab_acacia")
minetest.register_alias("mcl_stairs:slab_junglewood", "mcl_stairs:slab_jungle")
minetest.register_alias("mcl_stairs:slab_mangrove_wood", "mcl_stairs:slab_mangrove")
minetest.register_alias("mcl_stairs:slab_crimson_hyphae_wood", "mcl_stairs:slab_crimson")
minetest.register_alias("mcl_stairs:slab_warped_hyphae_wood", "mcl_stairs:slab_warped")
minetest.register_alias("mcl_stairs:slab_bamboo_plank", "mcl_stairs:slab_bamboo")
minetest.register_alias("mcl_stairs:slab_cherrywood", "mcl_stairs:slab_cherry_blossom")

minetest.register_alias("mcl_stairs:slab_wood_top", "mcl_stairs:slab_oak_top")
minetest.register_alias("mcl_stairs:slab_birchwood_top", "mcl_stairs:slab_birch_top")
minetest.register_alias("mcl_stairs:slab_sprucewood_top", "mcl_stairs:slab_spruce_top")
minetest.register_alias("mcl_stairs:slab_darkwood_top", "mcl_stairs:slab_dark_oak_top")
minetest.register_alias("mcl_stairs:slab_acaciawood_top", "mcl_stairs:slab_acacia_top")
minetest.register_alias("mcl_stairs:slab_junglewood_top", "mcl_stairs:slab_jungle_top")
minetest.register_alias("mcl_stairs:slab_mangrove_wood_top", "mcl_stairs:slab_mangrove_top")
minetest.register_alias("mcl_stairs:slab_crimson_hyphae_wood_top", "mcl_stairs:slab_crimson_top")
minetest.register_alias("mcl_stairs:slab_warped_hyphae_wood_top", "mcl_stairs:slab_warped_top")
minetest.register_alias("mcl_stairs:slab_bamboo_plank_top", "mcl_stairs:slab_bamboo_top")
minetest.register_alias("mcl_stairs:slab_cherrywood_top", "mcl_stairs:slab_cherry_blossom_top")

minetest.register_alias("mcl_stairs:slab_wood_double", "mcl_stairs:slab_oak_double")
minetest.register_alias("mcl_stairs:slab_birchwood_double", "mcl_stairs:slab_birch_double")
minetest.register_alias("mcl_stairs:slab_sprucewood_double", "mcl_stairs:slab_spruce_double")
minetest.register_alias("mcl_stairs:slab_darkwood_double", "mcl_stairs:slab_dark_oak_double")
minetest.register_alias("mcl_stairs:slab_acaciawood_double", "mcl_stairs:slab_acacia_double")
minetest.register_alias("mcl_stairs:slab_junglewood_double", "mcl_stairs:slab_jungle_double")
minetest.register_alias("mcl_stairs:slab_mangrove_wood_double", "mcl_stairs:slab_mangrove_double")
minetest.register_alias("mcl_stairs:slab_crimson_hyphae_wood_double", "mcl_stairs:slab_crimson_double")
minetest.register_alias("mcl_stairs:slab_warped_hyphae_wood_double", "mcl_stairs:slab_warped_double")
minetest.register_alias("mcl_stairs:slab_bamboo_plank_double", "mcl_stairs:slab_bamboo_double")
minetest.register_alias("mcl_stairs:slab_cherrywood_double", "mcl_stairs:slab_cherry_blossom_double")

minetest.register_alias("mcl_stairs:stair_tree_bark", "mcl_stairs:stair_oak_bark")
minetest.register_alias("mcl_stairs:stair_birchtree_bark", "mcl_stairs:stair_birch_bark")
minetest.register_alias("mcl_stairs:stair_sprucetree_bark", "mcl_stairs:stair_spruce_bark")
minetest.register_alias("mcl_stairs:stair_darktree_bark", "mcl_stairs:stair_dark_oak_bark")
minetest.register_alias("mcl_stairs:stair_acaciatree_bark", "mcl_stairs:stair_acacia_bark")
minetest.register_alias("mcl_stairs:stair_jungletree_bark", "mcl_stairs:stair_jungle_bark")
minetest.register_alias("mcl_stairs:stair_mangrove_tree_bark", "mcl_stairs:stair_mangrove_bark")
minetest.register_alias("mcl_stairs:stair_crimson_hyphae_tree_bark", "mcl_stairs:stair_crimson_bark")
minetest.register_alias("mcl_stairs:stair_warped_hyphae_tree_bark", "mcl_stairs:stair_warped_bark")
minetest.register_alias("mcl_stairs:stair_bamboo_block", "mcl_stairs:stair_bamboo_bark")

minetest.register_alias("mcl_stairs:stair_tree_bark_inner", "mcl_stairs:stair_oak_bark_inner")
minetest.register_alias("mcl_stairs:stair_birchtree_bark_inner", "mcl_stairs:stair_birch_bark_inner")
minetest.register_alias("mcl_stairs:stair_sprucetree_bark_inner", "mcl_stairs:stair_spruce_bark_inner")
minetest.register_alias("mcl_stairs:stair_darktree_bark_inner", "mcl_stairs:stair_dark_oak_bark_inner")
minetest.register_alias("mcl_stairs:stair_acaciatree_bark_inner", "mcl_stairs:stair_acacia_bark_inner")
minetest.register_alias("mcl_stairs:stair_jungletree_bark_inner", "mcl_stairs:stair_jungle_bark_inner")
minetest.register_alias("mcl_stairs:stair_mangrove_tree_bark_inner", "mcl_stairs:stair_mangrove_bark_inner")
minetest.register_alias("mcl_stairs:stair_crimson_hyphae_tree_bark_inner", "mcl_stairs:stair_crimson_bark_inner")
minetest.register_alias("mcl_stairs:stair_warped_hyphae_tree_bark_inner", "mcl_stairs:stair_warped_bark_inner")
minetest.register_alias("mcl_stairs:stair_bamboo_block_inner", "mcl_stairs:stair_bamboo_bark_inner")

minetest.register_alias("mcl_stairs:stair_tree_bark_outer", "mcl_stairs:stair_oak_bark_outer")
minetest.register_alias("mcl_stairs:stair_birchtree_bark_outer", "mcl_stairs:stair_birch_bark_outer")
minetest.register_alias("mcl_stairs:stair_sprucetree_bark_outer", "mcl_stairs:stair_spruce_bark_outer")
minetest.register_alias("mcl_stairs:stair_darktree_bark_outer", "mcl_stairs:stair_dark_oak_bark_outer")
minetest.register_alias("mcl_stairs:stair_acaciatree_bark_outer", "mcl_stairs:stair_acacia_bark_outer")
minetest.register_alias("mcl_stairs:stair_jungletree_bark_outer", "mcl_stairs:stair_jungle_bark_outer")
minetest.register_alias("mcl_stairs:stair_mangrove_tree_bark_outer", "mcl_stairs:stair_mangrove_bark_outer")
minetest.register_alias("mcl_stairs:stair_crimson_hyphae_tree_bark_outer", "mcl_stairs:stair_crimson_bark_outer")
minetest.register_alias("mcl_stairs:stair_warped_hyphae_tree_bark_outer", "mcl_stairs:stair_warped_bark_outer")
minetest.register_alias("mcl_stairs:stair_bamboo_block_outer", "mcl_stairs:stair_bamboo_bark_outer")

minetest.register_alias("mcl_stairs:slab_tree_bark", "mcl_stairs:slab_oak_bark")
minetest.register_alias("mcl_stairs:slab_birchtree_bark", "mcl_stairs:slab_birch_bark")
minetest.register_alias("mcl_stairs:slab_sprucetree_bark", "mcl_stairs:slab_spruce_bark")
minetest.register_alias("mcl_stairs:slab_darktree_bark", "mcl_stairs:slab_dark_oak_bark")
minetest.register_alias("mcl_stairs:slab_acaciatree_bark", "mcl_stairs:slab_acacia_bark")
minetest.register_alias("mcl_stairs:slab_jungletree_bark", "mcl_stairs:slab_jungle_bark")
minetest.register_alias("mcl_stairs:slab_mangrove_tree_bark", "mcl_stairs:slab_mangrove_bark")
minetest.register_alias("mcl_stairs:slab_crimson_hyphae_tree_bark", "mcl_stairs:slab_crimson_bark")
minetest.register_alias("mcl_stairs:slab_warped_hyphae_tree_bark", "mcl_stairs:slab_warped_bark")
minetest.register_alias("mcl_stairs:slab_bamboo_block", "mcl_stairs:slab_bamboo_bark")

minetest.register_alias("mcl_stairs:slab_tree_bark_top", "mcl_stairs:slab_oak_bark_top")
minetest.register_alias("mcl_stairs:slab_birchtree_bark_top", "mcl_stairs:slab_birch_bark_top")
minetest.register_alias("mcl_stairs:slab_sprucetree_bark_top", "mcl_stairs:slab_spruce_bark_top")
minetest.register_alias("mcl_stairs:slab_darktree_bark_top", "mcl_stairs:slab_dark_oak_bark_top")
minetest.register_alias("mcl_stairs:slab_acaciatree_bark_top", "mcl_stairs:slab_acacia_bark_top")
minetest.register_alias("mcl_stairs:slab_jungletree_bark_top", "mcl_stairs:slab_jungle_bark_top")
minetest.register_alias("mcl_stairs:slab_mangrove_tree_bark_top", "mcl_stairs:slab_mangrove_bark_top")
minetest.register_alias("mcl_stairs:slab_crimson_hyphae_tree_bark_top", "mcl_stairs:slab_crimson_bark_top")
minetest.register_alias("mcl_stairs:slab_warped_hyphae_tree_bark_top", "mcl_stairs:slab_warped_bark_top")
minetest.register_alias("mcl_stairs:slab_bamboo_block_top", "mcl_stairs:slab_bamboo_bark_top")

minetest.register_alias("mcl_stairs:slab_tree_bark_double", "mcl_stairs:slab_oak_bark_double")
minetest.register_alias("mcl_stairs:slab_birchtree_bark_double", "mcl_stairs:slab_birch_bark_double")
minetest.register_alias("mcl_stairs:slab_sprucetree_bark_double", "mcl_stairs:slab_spruce_bark_double")
minetest.register_alias("mcl_stairs:slab_darktree_bark_double", "mcl_stairs:slab_dark_oak_bark_double")
minetest.register_alias("mcl_stairs:slab_acaciatree_bark_double", "mcl_stairs:slab_acacia_bark_double")
minetest.register_alias("mcl_stairs:slab_jungletree_bark_double", "mcl_stairs:slab_jungle_bark_double")
minetest.register_alias("mcl_stairs:slab_mangrove_tree_bark_double", "mcl_stairs:slab_mangrove_bark_double")
minetest.register_alias("mcl_stairs:slab_crimson_hyphae_tree_bark_double", "mcl_stairs:slab_crimson_bark_double")
minetest.register_alias("mcl_stairs:slab_warped_hyphae_tree_bark_double", "mcl_stairs:slab_warped_bark_double")
minetest.register_alias("mcl_stairs:slab_bamboo_block_double", "mcl_stairs:slab_bamboo_bark_double")

minetest.register_alias("mesecons_button:button_wood_on","mesecons_button:button_oak_on")
minetest.register_alias("mesecons_button:button_sprucewood_on","mesecons_button:button_spruce_on")
minetest.register_alias("mesecons_button:button_acaciawood_on","mesecons_button:button_acacia_on")
minetest.register_alias("mesecons_button:button_junglewood_on","mesecons_button:button_jungle_on")
minetest.register_alias("mesecons_button:button_birchwood_on","mesecons_button:button_birch_on")
minetest.register_alias("mesecons_button:button_darkwood_on","mesecons_button:button_dark_oak_on")
minetest.register_alias("mesecons_button:button_warped_hyphae_on","mesecons_button:button_warped_on")
minetest.register_alias("mesecons_button:button_crimson_hyphae_on","mesecons_button:button_crimson_on")
minetest.register_alias("mesecons_button:button_mangrove_wood_on","mesecons_button:button_mangrove_on")
minetest.register_alias("mesecons_button:button_cherrywood_on","mesecons_button:button_cherry_blossom_on")

minetest.register_alias("mesecons_button:button_wood_off","mesecons_button:button_oak_off")
minetest.register_alias("mesecons_button:button_sprucewood_off","mesecons_button:button_spruce_off")
minetest.register_alias("mesecons_button:button_acaciawood_off","mesecons_button:button_acacia_off")
minetest.register_alias("mesecons_button:button_junglewood_off","mesecons_button:button_jungle_off")
minetest.register_alias("mesecons_button:button_birchwood_off","mesecons_button:button_birch_off")
minetest.register_alias("mesecons_button:button_darkwood_off","mesecons_button:button_dark_oak_off")
minetest.register_alias("mesecons_button:button_warped_hyphae_off","mesecons_button:button_warped_off")
minetest.register_alias("mesecons_button:button_crimson_hyphae_off","mesecons_button:button_crimson_off")
minetest.register_alias("mesecons_button:button_mangrove_wood_off","mesecons_button:button_mangrove_off")
minetest.register_alias("mesecons_button:button_cherrywood_off","mesecons_button:button_cherry_blossom_off")

minetest.register_alias("mesecons_pressureplates:pressure_plate_wood_on","mesecons_pressureplates:pressure_plate_oak_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_sprucewood_on","mesecons_pressureplates:pressure_plate_spruce_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_acaciawood_on","mesecons_pressureplates:pressure_plate_acacia_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_junglewood_on","mesecons_pressureplates:pressure_plate_jungle_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_birchwood_on","mesecons_pressureplates:pressure_plate_birch_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_darkwood_on","mesecons_pressureplates:pressure_plate_dark_oak_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_warped_hyphae_on","mesecons_pressureplates:pressure_plate_warped_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_crimson_hyphae_on","mesecons_pressureplates:pressure_plate_crimson_on")
minetest.register_alias("mesecons_pressureplates:pressure_plate_mangrove_wood_on","mesecons_pressureplates:pressure_plate_mangrove_on")
minetest.register_alias("mcl_cherry_blossom:pressure_plate_cherrywood_on","mesecons_pressureplates:pressure_plate_cherry_blossom_on")

minetest.register_alias("mesecons_pressureplates:pressure_plate_wood_off","mesecons_pressureplates:pressure_plate_oak_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_sprucewood_off","mesecons_pressureplates:pressure_plate_spruce_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_acaciawood_off","mesecons_pressureplates:pressure_plate_acacia_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_junglewood_off","mesecons_pressureplates:pressure_plate_jungle_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_birchwood_off","mesecons_pressureplates:pressure_plate_birch_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_darkwood_off","mesecons_pressureplates:pressure_plate_dark_oak_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_warped_hyphae_off","mesecons_pressureplates:pressure_plate_warped_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_crimson_hyphae_off","mesecons_pressureplates:pressure_plate_crimson_off")
minetest.register_alias("mesecons_pressureplates:pressure_plate_mangrove_wood_off","mesecons_pressureplates:pressure_plate_mangrove_off")
minetest.register_alias("mcl_cherry_blossom:pressure_plate_cherrywood_off","mesecons_pressureplates:pressure_plate_cherry_blossom_off")

local function alias_signs(oldwood,newwood)
	minetest.register_alias("mcl_signs:wall_sign"..oldwood, "mcl_signs:wall_sign".. newwood)
end --standing signs conversion in mcl_signs/compat.lua
minetest.register_alias("mcl_signs:sign","mcl_signs:wall_sign_oak")

alias_signs("","_oak")
alias_signs("_acaciawood","_acacia")
alias_signs("_junglewood","_jungle")
alias_signs("_birchwood","_birch")
alias_signs("_darkwood","_dark_oak")
alias_signs("_sprucewood","_spruce")
alias_signs("_mangrove_wood","_mangrove")
alias_signs("_crimson_hyphae_wood","_crimson")
alias_signs("_warped_hyphae_wood","_warped")
alias_signs("_cherrywood","_cherry_blossom")

minetest.register_alias("mcl_boats:boat","mcl_boats:boat_oak")
minetest.register_alias("mcl_boats:boat_cherry","mcl_boats:boat_cherry_blossom")
minetest.register_alias("mcl_boats:boat_obsidian","mcl_boats:boat_oak")

local function alias_chest_boat(oldwood,newwood)
	newwood = newwood or oldwood
	minetest.register_alias("mcl_boats:chest_boat"..oldwood,"mcl_boats:boat"..newwood.."_chest")
end
alias_chest_boat("","_oak")
alias_chest_boat("_acacia")
alias_chest_boat("_birch")
alias_chest_boat("_cherry", "_cherry_blossom")
alias_chest_boat("_dark_oak")
alias_chest_boat("_jungle")
alias_chest_boat("_mangrove")
alias_chest_boat("_spruce")
