.TH "miceamaze" "6" "" "miceamaze" ""
.SH "NAME"
MiceAmaze \- video game with mice in a maze
.SH "SYNOPSIS"
.
.B miceamaze
[\fIOPTIONS\fR]
.
.SH "DESCRIPTION"
MiceAmaze is a free video game that features a maze with mice and snakes.
The goal is to bring the most mice to your house by placing arrows on the
maze floor. But beware the snakes that want to eat them!
.SH "OPTIONS"
.
.TP 
.B \--window
start in window mode (not fullscreen)
.TP 
.B \--fullscreen
start in fullscreen mode
.
.SH "COPYRIGHT"
.
Copyright (c) 2012, River CHAMPEIMONT
.
