
/**
 * All game sprites
 */
var SpriteTypes = {

    Player: 0,
    Grenade: 2,
    ShadowSmall: 3,
    Null: 4,
    Enemy: 5,
    Bullet: 6,

    Explosion: 12,
    Shrub: 13,
    Tree: 14,
    BuildingRoof: 15,
    Snowman: 16,
    Shrub2: 17,
    Waterfall: 18,
    Bird2_Left: 19,

    BuildingDoor: 20,
    Player_Rank: 21,
    Player_Shadow: 22,
    BloodTrail: 23,
    GroundHole: 24,
    BuildingDoor2: 25,
    Floating_Dead_Soldier: 27,
    Text_Complete: 28,
    Text_Mission: 29,

    Text_Phase: 30,
    Rocket: 33,
    Text_GameOver: 34,
    Shadow: 35,
    Enemy_Rocket: 36,
    GrenadeBox: 37,
    RocketBox: 38,
    Building_Explosion: 39,

    Helicopter_Grenade_Enemy: 40,
    Flashing_Light: 41,
    Helicopter_Grenade2_Enemy: 42,
    Helicopter_Missile_Enemy: 43,
    Helicopter_Homing_Enemy: 44,
    Missile: 45,
    MissileHoming: 46,
    Sparks: 47,
    FireTrail: 48,
    Helicopter_Grenade2_Human: 49,

    Helicopter_Grenade_Human: 50,
    Helicopter_Missile_Human: 51,
    Helicopter_Homing_Human: 52,
    Helicopter_PropCrash: 53,
    Mine: 54,
    Mine2: 55,
    Spike: 56,
    Smoke: 57,
    Text_Try: 58,
    Text_Again: 59,

    BoilingPot: 60,
    Civilian: 61,
    Civilian2: 62,
    VehicleNoGun_Human: 63,
    VehicleGun_Human: 64,
    Tank_Human: 65,
    Bird_Left: 66,
    Bird_Right: 67,
    Seal: 68,
    Tank_Enemy: 69,

    Civilian_Spear: 70,
    Civilian_Spear2: 71,
    Hostage: 72,
    Hostage_Rescue_Tent: 73,
    Door_Civilian: 74,
    Door2_Civilian: 75,
    Door_Civilian_Spear: 76,
    Cannon: 77,
    Turret_Missile_Human: 78,
    Turret_Missile2_Human: 79,

    VehicleNoGun_Enemy: 80,
    VehicleGun_Enemy: 81,
    Vehicle_Unk_Enemy: 82,
    Civilian_Invisible: 83,
    Turret_Missile_Enemy: 84,
    Turret_Missile2_Enemy: 85,
    Vehicle_Sinking_1: 86,
    Vehicle_Sinking_2: 87,
    BuildingDoor3: 88,
    Explosion2: 89,

    Door_Civilian_Rescue: 90,
    Seal_Mine: 91,
    Spider_Mine: 92,
    Bonus_RankToGeneral: 93,
    Bonus_Rockets: 94,
    Bonus_Armour: 95,
    Bonus_RankHomingInvin_SquadLeader: 96,
    MissileHoming2: 97,
    Bonus_RankHomingInvin_Squad: 98,
    Helicopter_CallPad: 99,

    BuildingDoor_Reinforced: 100,
    Helicopter_Grenade2_Human_Called: 101,
    Helicopter_Grenade_Human_Called: 102,
    Helicopter_Missile_Human_Called: 103,
    Helicopter_Homing_Human_Called: 104,
    Turret_HomingMissile_Enemy: 105,
    Enemy_Leader: 106,
    Helicopter_Homing_Enemy2: 107,
    Computer_1: 108,
    Computer_2: 109,
    Computer_3: 110,

    // Cannon Fodder 2
    UFO_Callpad: 111,

    Turret_Cannon_Invulnerable: 112,
    Turret_Missile_Invulnerable: 113,
    Looping_Vehicle_Left: 114,
    Looping_Vehicle_Right: 115,

    Looping_Vehicle_Up: 116,
    Looping_Vehicle_Down: 117
};
