#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"
LOGERR="$GAMEDIR/patch_error.txt"

# Redirect output and error to the log file
rm -rf $LOGFILE $LOGERR
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="sonictt16b.port"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

unzip_apk() {
    # Unzip the user-provided apk if it exists
    if [ -f "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk" ]; then
    echo "Extracting apk file..."
        mkdir -p "$GAMEDIR/tmp"
        unzip "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk" -d "$GAMEDIR/tmp"
        # Zip the lib folder into the .port file
        (cd "$GAMEDIR/tmp" && zip -r -0 "$GAMEDIR/$DATAFILE" lib)
        # Move the assets folder to the $GAMEDIR
        mv "$GAMEDIR/tmp/assets" "$GAMEDIR" && rm -rf "$GAMEDIR/tmp"
        rm -rf "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk"
    fi
}

apply_xdelta() {
    # Check if the game.droid file exists and apply xdelta
    if [ -f "$DATADIR/game.droid" ]; then
        output=$(xdelta3 -d -s "$DATADIR/game.droid" -f "./tools/patches/sonictt16b.xdelta" "$DATADIR/game2.droid" 2>&1)
        if [ $? -eq 0 ]; then
            echo "Patch applied successfully"
            echo "$output"
            rm "$DATADIR/game.droid" && mv "$DATADIR/game2.droid" "$DATADIR/game.droid"
        else
            echo "Failed to apply patch"
            echo "$output"
            mv $LOGFILE $LOGERR
            exit 1
        fi
    else
        echo "No data.win file found to patch!"
    fi
}

compress_audio() {
    mkdir -p "$TMPDIR"

    # Run the compression tool
    PYTHON=$(which python3)
    if [ "$PREPATCH" != 1 ]; then
        echo "Running GMTools on data and audiogroups."
        $PYTHON ./tools/gmKtool.py -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"
    fi

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$DATADIR"
        echo "Moved compressed files to $DATADIR."
        rm -rf "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
    else
        echo "Audio compression failed."
        echo "Cleaning up temporary directory $TMPDIR."
        rm -rf "$TMPDIR"
    fi
}

zip_archive() {
        zip -r -0 $DATAFILE ./assets/
        mkdir -p saves
        rm -rf assets
}

process_game() {
    unzip_apk
    # Delete unnecessary files
    rm -rf $DATADIR/*.exe $DATADIR/*.png $DATADIR/.txt $DATADIR/.gitkeep
    echo "Removed unnecessary files"
    sleep 1
    echo "Applying xdelta patch"
    apply_xdelta
    sleep 1
    echo "Compressing audio..."
    compress_audio
    sleep 1
    echo "Finishing up..."
    zip_archive
    sleep 1
	
    # Final completion message
    echo "Patching process complete!"
}

# Call the function
process_game