#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Patch failure function
patch_failure() {
    mv "$LOGFILE" "$LOGERR"
    $ESUDO umount "$TOOLKIT"
    echo "Patching process failed."
    exit 1
}

# Mount the GMToolkit runtime
TOOLKIT="$HOME/gmtoolkit"
RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
if [ -f "$RUNTIME" ]; then
    $ESUDO mkdir -p "$TOOLKIT"
    $ESUDO umount "$TOOLKIT" || true
    $ESUDO mount "$RUNTIME" "$TOOLKIT"
else
    echo "This port requires the GMToolkit runtime. Please download it."
    sleep 2
    patch_failure
fi

# Exports
export PATH="$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export DATADIR="$GAMEDIR/assets"
export DATAFILE="sonictt16b.port"
export TMPDIR="$GAMEDIR/tmp"

# Permissions
chmod 666 /dev/uinput

cd "$GAMEDIR"

# Set up trap for cleaning TMPDIR on exit
trap 'rm -rf "$TMPDIR"; echo "Cleaned up temporary files." >> "$LOGFILE"' 0

# Attempt to get SAVEDIR from gmloader.json using jq
if command -v jq >/dev/null 2>&1; then
    SAVEDIR=$(jq -r '.save_dir // empty' "$GAMEDIR/gmloader.json" 2>/dev/null)
else
    SAVEDIR="$GAMEDIR/saves"
fi

# Test for commands: python, zip
PYTHON=$(which python3)
if [ -z "$PYTHON" ]; then
    echo "Missing Python!"
    patch_failure
fi

ZIP=$(which zip)
if [ -z "$ZIP" ]; then
    echo "Missing zip!"
    patch_failure
fi

unzip_apk() {
    # Unzip the user-provided apk if it exists
    if [ -f "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk" ]; then
    echo "Extracting apk file..."
        mkdir -p "$GAMEDIR/tmp"
        unzip "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk" -d "$GAMEDIR/tmp"
        # Zip the lib folder into the .port file
        (cd "$GAMEDIR/tmp" && zip -r -0 "$GAMEDIR/$DATAFILE" lib)
        # Move the assets folder to the $GAMEDIR
        mv "$GAMEDIR/tmp/assets" "$GAMEDIR" && rm -rf "$GAMEDIR/tmp"
        rm -rf "$GAMEDIR/sonic-triple-trouble-16-bit-v1-2-8.apk"
    fi
}

apply_xdelta() {
    # Check if the game.droid file exists and apply xdelta
    if [ -f "$DATADIR/game.droid" ]; then
        output=$($controlfolder/xdelta3 -d -s "$DATADIR/game.droid" -f "$TOOLDIR/patches/sonictt16b.xdelta" "$DATADIR/game2.droid" 2>&1)
        if [ $? -eq 0 ]; then
            echo "Patch applied successfully"
            echo "$output"
            rm "$DATADIR/game.droid" && mv "$DATADIR/game2.droid" "$DATADIR/game.droid"
        else
            echo "Failed to apply patch"
            echo "$output"
            mv $LOGFILE $LOGERR
            exit 1
        fi
    else
        echo "No data.win file found to patch!"
    fi
}

compress_audio() {  
    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
        mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
        echo "Audio compression applied successfully."
    else
        # Failure
        echo "Audio compression failed for $GAMEFILE."
        rmdir "$TMPDIR"
        patch_failure
    fi
}

zip_archive() {
        zip -r -0 $DATAFILE ./assets/
        mkdir -p saves
        rm -rf assets
}

process_game() {
    unzip_apk
    # Delete unnecessary files
    rm -rf $DATADIR/*.exe $DATADIR/*.png $DATADIR/.txt $DATADIR/.gitkeep
    echo "Removed unnecessary files"
    echo "Applying xdelta patch"
    apply_xdelta || patch_failure
    echo "Compressing audio..."
    compress_audio || patch_failure
    echo "Finishing up..."
    zip_archive || patch_failure
    
    # Unmount runtimes
    $ESUDO umount "$TOOLKIT"
	
    # Final completion message
    echo "Patching process complete!"
}

# Call the function
process_game