require 'Entities'

local levels = {
    -- To test all kinds of entities
    ['LDEBUG'] = {
        ['type'] = 'LevelA',
        ['entities'] = {
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 80, ['y'] = 80} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 105, ['y'] = 150} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 120, ['y'] = 100} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 20, ['y'] = 130} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 75, ['y'] = 130} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 130, ['y'] = 200} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 105, ['y'] = 210} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 243, ['y'] = 182 } },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 200, ['y'] = 150 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 300, ['y'] = 60 }, ['dir'] = 'Left', },
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 200, ['y'] = 80 }, },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 100, ['y'] = 80 }, },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 150, ['y'] = 120 }, },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 150, ['y'] = 160 }, },
        }
    },

    ['L1_1'] = {
        ['type'] = 'LevelB',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 54, ['y'] = 72 }, },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 239, ['y'] = 73 }, },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 198, ['y'] = 149 }, },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 139, ['y'] = 201 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 239, ['y'] = 92 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 213, ['y'] = 103 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 70, ['y'] = 106 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 96, ['y'] = 140 }, },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 180, ['y'] = 107 }, },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 294, ['y'] = 191 }, },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 45, ['y'] = 219 }, },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 42, ['y'] = 140 }, },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 165, ['y'] = 172 }, },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 28, ['y'] = 75 }, },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 227, ['y'] = 106 }, },
        }
    },
    ['L1_2'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 259, ['y'] = 68 }, },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 32, ['y'] = 93 }, },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 219, ['y'] = 142 }, },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 94, ['y'] = 202 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 60, ['y'] = 70 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 256, ['y'] = 85 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 99, ['y'] = 104 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 242, ['y'] = 106 }, },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 243, ['y'] = 123 }, },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 180, ['y'] = 107 }, },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 129, ['y'] = 165 }, },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 67, ['y'] = 184 }, },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 21, ['y'] = 121 }, },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 292, ['y'] = 139 }, },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 202, ['y'] = 202 }, },
        }
    },
    ['L1_3'] = {
        ['type'] = 'LevelA',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 142, ['y'] = 109} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 230, ['y'] = 128} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 195, ['y'] = 178} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 263, ['y'] = 104} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 188, ['y'] = 139} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 50, ['y'] = 158} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 68} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 74, ['y'] = 70} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 88} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 214, ['y'] = 116} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 288, ['y'] = 118} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 35, ['y'] = 142} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 70, ['y'] = 180} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 153, ['y'] = 200} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 38, ['y'] = 98} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 243, ['y'] = 182 } },
        }
    },
    ['L2_1'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 267, ['y'] = 86} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 230, ['y'] = 128} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 127, ['y'] = 165} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 37, ['y'] = 104} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 84, ['y'] = 143} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 170, ['y'] = 160} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 243, ['y'] = 206} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 249, ['y'] = 72} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 151, ['y'] = 107} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 275, ['y'] = 124} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 192, ['y'] = 126} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 107, ['y'] = 136} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 61, ['y'] = 166} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 213, ['y'] = 179} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 17, ['y'] = 98} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 278, ['y'] = 197} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 1, ['y'] = 168} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 197, ['y'] = 193} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 97, ['y'] = 190} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 229, ['y'] = 154 } },
        }
    },
    ['L2_2'] = {
        ['type'] = 'LevelB',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 96, ['y'] = 106} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 60, ['y'] = 170} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 52, ['y'] = 221} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 22, ['y'] = 68} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 2, ['y'] = 115} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 83, ['y'] = 144} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 8, ['y'] = 156} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 249, ['y'] = 72} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 202, ['y'] = 79} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 213, ['y'] = 113} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 275, ['y'] = 125} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 182, ['y'] = 140} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 212, ['y'] = 180} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 245, ['y'] = 211} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 224, ['y'] = 146} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 277, ['y'] = 149} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 190, ['y'] = 169} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 8, ['y'] = 191} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 268, ['y'] = 197} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 26, ['y'] = 91} },
        }
    },
    ['L2_3'] = {
        ['type'] = 'LevelB',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 223, ['y'] = 84} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 127, ['y'] = 166} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 60, ['y'] = 170} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 37, ['y'] = 105} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 83, ['y'] = 144} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 8, ['y'] = 156} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 174, ['y'] = 158} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 249, ['y'] = 72} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 202, ['y'] = 79} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 34, ['y'] = 94} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 213, ['y'] = 113} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 275, ['y'] = 125} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 107, ['y'] = 136} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 212, ['y'] = 180} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 11, ['y'] = 93} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 224, ['y'] = 146} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 278, ['y'] = 197} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 16, ['y'] = 190} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 81, ['y'] = 206} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 136, ['y'] = 184} },
        }
    },
    ['L3_1'] = {
        ['type'] = 'LevelA',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 143, ['y'] = 108} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 231, ['y'] = 129} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 195, ['y'] = 178} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 265, ['y'] = 104} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 189, ['y'] = 140} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 48, ['y'] = 156} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 266, ['y'] = 167} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 69} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 74, ['y'] = 70} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 88} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 216, ['y'] = 116} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 288, ['y'] = 117} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 34, ['y'] = 142} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 69, ['y'] = 179} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 154, ['y'] = 201} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 38, ['y'] = 98} },
        }
    },
    ['L3_2'] = {
        ['type'] = 'LevelA',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 155, ['y'] = 108} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 231, ['y'] = 129} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 231, ['y'] = 171} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 258, ['y'] = 128} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 214, ['y'] = 145} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 48, ['y'] = 156} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 261, ['y'] = 157} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 69} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 74, ['y'] = 70} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 88} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 216, ['y'] = 116} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 288, ['y'] = 117} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 34, ['y'] = 126} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 207, ['y'] = 204} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 77, ['y'] = 217} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 27, ['y'] = 72} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 244, ['y'] = 154} },
        }
    },
    ['L3_3'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 138, ['y'] = 108} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 165, ['y'] = 131} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 227, ['y'] = 175} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 264, ['y'] = 127} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 205, ['y'] = 145} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 264, ['y'] = 157} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 56, ['y'] = 160} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 69} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 74, ['y'] = 70} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 88} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 216, ['y'] = 116} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 288, ['y'] = 117} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 34, ['y'] = 126} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 237, ['y'] = 138} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = -10, ['y'] = 166} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 183, ['y'] = 141} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 250, ['y'] = 177} },
        }
    },
    ['L4_1'] = {
        ['type'] = 'LevelE',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 189, ['y'] = 146} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 73, ['y'] = 88} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 259, ['y'] = 99} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 56, ['y'] = 197} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 63, ['y'] = 80} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 209, ['y'] = 95} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 217, ['y'] = 104} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 222, ['y'] = 118} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 181, ['y'] = 117} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 84, ['y'] = 176} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 174, ['y'] = 183} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 240, ['y'] = 110} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 80, ['y'] = 134} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 214, ['y'] = 144} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 138, ['y'] = 182} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = -12, ['y'] = 117 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 108, ['y'] = 168 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 328, ['y'] = 158 }, ['dir'] = 'Left', },
        }
    },
    ['L4_2'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 155, ['y'] = 108} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 73, ['y'] = 88} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 259, ['y'] = 99} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 88, ['y'] = 206} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 52, ['y'] = 75} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 96, ['y'] = 78} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 114, ['y'] = 107} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 215, ['y'] = 116} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 293, ['y'] = 99} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 192, ['y'] = 123} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 31, ['y'] = 135} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 175, ['y'] = 172} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 54, ['y'] = 185} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 233, ['y'] = 91} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 119, ['y'] = 133} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 41, ['y'] = 122 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 156, ['y'] = 164 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 218, ['y'] = 85 }, ['dir'] = 'Left', },
        }
    },
    ['L4_3'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 153, ['y'] = 165} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 268, ['y'] = 156} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 34, ['y'] = 160} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 88, ['y'] = 206} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 15, ['y'] = 104} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 215, ['y'] = 144} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 106, ['y'] = 163} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 91, ['y'] = 169} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 181, ['y'] = 117} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 175, ['y'] = 172} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 53, ['y'] = 185} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 241, ['y'] = 153} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 129, ['y'] = 176} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 89, ['y'] = 77 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 251, ['y'] = 92 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 65, ['y'] = 111 }, ['dir'] = 'Right', },
        }
    },
    ['L5_1'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 290, ['y'] = 196} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 169, ['y'] = 108} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 235, ['y'] = 111} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 261, ['y'] = 225} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 72} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 79, ['y'] = 79} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 197, ['y'] = 148} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 64, ['y'] = 180} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 257, ['y'] = 98} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 112, ['y'] = 131} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 31, ['y'] = 136} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 92, ['y'] = 201} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = -17, ['y'] = 183} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 306, ['y'] = 160} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 218, ['y'] = 192} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 284, ['y'] = 182} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 36, ['y'] = 194} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 253, ['y'] = 207} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 278, ['y'] = 210} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 44, ['y'] = 129 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 289, ['y'] = 169 }, ['dir'] = 'Left', },
        }
    },
    ['L5_2'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 172, ['y'] = 145} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 55, ['y'] = 87} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 235, ['y'] = 111} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 91, ['y'] = 152} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 54, ['y'] = 72} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 79, ['y'] = 79} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 197, ['y'] = 148} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 64, ['y'] = 180} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 257, ['y'] = 98} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 112, ['y'] = 131} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 31, ['y'] = 136} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 92, ['y'] = 201} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 174, ['y'] = 185} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = -17, ['y'] = 183} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 306, ['y'] = 160} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 218, ['y'] = 192} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 284, ['y'] = 182} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 36, ['y'] = 194} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 253, ['y'] = 207} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 80, ['y'] = 120 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 259, ['y'] = 169 }, ['dir'] = 'Left', },
        }
    },
    ['L5_3'] = {
        ['type'] = 'LevelB',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 172, ['y'] = 145} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 55, ['y'] = 87} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 235, ['y'] = 111} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 86, ['y'] = 151} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 42, ['y'] = 71} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 197, ['y'] = 148} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 133, ['y'] = 162} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 64, ['y'] = 180} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 257, ['y'] = 98} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 112, ['y'] = 131} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 31, ['y'] = 136} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 174, ['y'] = 185} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 113, ['y'] = 215} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = -17, ['y'] = 183} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 233, ['y'] = 216} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 214, ['y'] = 100} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 293, ['y'] = 146} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 9, ['y'] = 162} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 144, ['y'] = 177} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 80, ['y'] = 120 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 250, ['y'] = 166 }, ['dir'] = 'Left', },
        }
    },
    ['L6_1'] = {
        ['type'] = 'LevelE',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 294, ['y'] = 176} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 63, ['y'] = 188} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 248, ['y'] = 198} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 6, ['y'] = 164} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 121, ['y'] = 189} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 183, ['y'] = 190} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 242, ['y'] = 72} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 36, ['y'] = 80} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 203, ['y'] = 97} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 52, ['y'] = 133} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 270, ['y'] = 134} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 237, ['y'] = 161} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 94, ['y'] = 166} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 119, ['y'] = 95} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 4, ['y'] = 121} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 264, ['y'] = 183} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 145, ['y'] = 168} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 158, ['y'] = 139} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 49, ['y'] = 118 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 231, ['y'] = 227 }, ['dir'] = 'Left', },
        }
    },
    ['L6_2'] = {
        ['type'] = 'LevelE',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 249, ['y'] = 71} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 200, ['y'] = 92} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 58, ['y'] = 155} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 51, ['y'] = 81} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 119, ['y'] = 143} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 176, ['y'] = 213} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 52, ['y'] = 132} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 240, ['y'] = 147} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 250, ['y'] = 155} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 266, ['y'] = 160} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 237, ['y'] = 162} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 95, ['y'] = 166} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 109, ['y'] = 205} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 217, ['y'] = 145} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 39, ['y'] = 209} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 208, ['y'] = 219} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 301, ['y'] = 189} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 269, ['y'] = 111} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 30, ['y'] = 112 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 255, ['y'] = 121 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 91, ['y'] = 179 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 234, ['y'] = 194 }, ['dir'] = 'Left', },
        }
    },
    ['L6_3'] = {
        ['type'] = 'LevelC',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 231, ['y'] = 91} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 115, ['y'] = 95} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 45, ['y'] = 176} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 19, ['y'] = 90} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 166, ['y'] = 151} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 294, ['y'] = 153} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 195, ['y'] = 166} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 255, ['y'] = 167} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 68, ['y'] = 170} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 244, ['y'] = 175} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 282, ['y'] = 185} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 109, ['y'] = 205} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 250, ['y'] = 208} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 5, ['y'] = 185} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 39, ['y'] = 209} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 208, ['y'] = 219} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 123, ['y'] = 204} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 253, ['y'] = 182} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 27, ['y'] = 120 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 306, ['y'] = 120 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 126, ['y'] = 140 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 237, ['y'] = 189 }, ['dir'] = 'Left', },
        }
    },
    ['L7_1'] = {
        ['type'] = 'LevelC',
        ['entities'] = {
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 224, ['y'] = 114} },
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 91, ['y'] = 131} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 230, ['y'] = 109} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 33, ['y'] = 147} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 249, ['y'] = 91} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 69, ['y'] = 155} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 166, ['y'] = 100} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 59, ['y'] = 101} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 290, ['y'] = 93} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 93, ['y'] = 173} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 238, ['y'] = 182} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = -7, ['y'] = 197} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 100, ['y'] = 216} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 233, ['y'] = 140} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 194, ['y'] = 74 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 306, ['y'] = 86 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 284, ['y'] = 133 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 16, ['y'] = 144 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 153, ['y'] = 157 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 54, ['y'] = 195 }, ['dir'] = 'Right', },
        }
    },
    ['L7_2'] = {
        ['type'] = 'LevelA',
        ['entities'] = {
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 239, ['y'] = 104} },
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 32, ['y'] = 184} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 30, ['y'] = 101} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 118, ['y'] = 136} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 84, ['y'] = 121} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 202, ['y'] = 121} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 3, ['y'] = 138} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 167, ['y'] = 158} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 274, ['y'] = 102} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 91, ['y'] = 168} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 176, ['y'] = 167} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = -7, ['y'] = 197} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 128, ['y'] = 212} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 61, ['y'] = 111} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 305, ['y'] = 83 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 14, ['y'] = 87 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 210, ['y'] = 97 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 42, ['y'] = 163 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 271, ['y'] = 160 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 77, ['y'] = 204 }, ['dir'] = 'Right', },
        }
    },
    ['L7_3'] = {
        ['type'] = 'LevelA',
        ['entities'] = {
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 224, ['y'] = 114} },
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 69, ['y'] = 136} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 230, ['y'] = 109} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 246, ['y'] = 161} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 125, ['y'] = 171} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 194, ['y'] = 171} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 167, ['y'] = 101} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 39, ['y'] = 108} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 16, ['y'] = 73} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 289, ['y'] = 91} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 75, ['y'] = 184} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 222, ['y'] = 188} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 149, ['y'] = 203} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 247, ['y'] = 110} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 104, ['y'] = 86 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 74, ['y'] = 125 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 274, ['y'] = 136 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 17, ['y'] = 164 }, ['dir'] = 'Right', },
        }
    },
    ['L8_1'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 253, ['y'] = 92} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 25, ['y'] = 116} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 80, ['y'] = 146} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 203, ['y'] = 153} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 269, ['y'] = 203} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 293, ['y'] = 177} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 20, ['y'] = 208} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 285, ['y'] = 72} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 59, ['y'] = 85} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 117, ['y'] = 101} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 185, ['y'] = 123} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 232, ['y'] = 143} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 38, ['y'] = 168} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 113, ['y'] = 176} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 188, ['y'] = 202} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 15, ['y'] = 122 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 61, ['y'] = 155 }, ['dir'] = 'Right', },
        }
    },
    ['L8_2'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 150, ['y'] = 87} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 107, ['y'] = 129} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 191, ['y'] = 128} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 70, ['y'] = 174} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 226, ['y'] = 179} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 296, ['y'] = 169} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 3, ['y'] = 174} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 285, ['y'] = 72} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 59, ['y'] = 85} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 117, ['y'] = 101} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 185, ['y'] = 123} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 232, ['y'] = 143} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 38, ['y'] = 168} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 113, ['y'] = 176} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 188, ['y'] = 202} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 15, ['y'] = 122 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 61, ['y'] = 155 }, ['dir'] = 'Right', },
        }
    },
    ['L8_3'] = {
        ['type'] = 'LevelB',
        ['entities'] = {
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 13, ['y'] = 75} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 170, ['y'] = 89} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 72, ['y'] = 113} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 241, ['y'] = 115} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 10, ['y'] = 140} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 267, ['y'] = 145} },
            { ['type'] = 'MiniRock', ['pos'] = { ['x'] = 132, ['y'] = 157} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 285, ['y'] = 68} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 57, ['y'] = 84} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 232, ['y'] = 85} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 116, ['y'] = 120} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 71, ['y'] = 130} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 304, ['y'] = 133} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 222, ['y'] = 134} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 50, ['y'] = 147} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 181, ['y'] = 163} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 24, ['y'] = 109} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 275, ['y'] = 109} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 0, ['y'] = 170} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 217, ['y'] = 171} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 136, ['y'] = 182} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 286, ['y'] = 206} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 60, ['y'] = 208} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 79, ['y'] = 105} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 305, ['y'] = 175} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 42, ['y'] = 208} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 28, ['y'] = 215} },
        }
    },
    ['L9_1'] = {
        ['type'] = 'LevelA',
        ['entities'] = {
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 159, ['y'] = 178} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 277, ['y'] = 194} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 309, ['y'] = 64} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = -4, ['y'] = 84} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 310, ['y'] = 143} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 12, ['y'] = 172} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 261, ['y'] = 208} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 175, ['y'] = 217} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 85, ['y'] = 218} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 143, ['y'] = 88} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 48, ['y'] = 175} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 213, ['y'] = 182} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 3, ['y'] = 115} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 292, ['y'] = 157} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 276, ['y'] = 104 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 44, ['y'] = 135 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 216, ['y'] = 148 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 86, ['y'] = 167 }, ['dir'] = 'Right', },
        }
    },
    ['L9_2'] = {
        ['type'] = 'LevelB',
        ['entities'] = {
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 164, ['y'] = 189} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 277, ['y'] = 194} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 230, ['y'] = 78} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 62, ['y'] = 81} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 112, ['y'] = 147} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 146, ['y'] = 147} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 181, ['y'] = 147} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 6, ['y'] = 205} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 291, ['y'] = 206} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 58, ['y'] = 66} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 48, ['y'] = 175} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 213, ['y'] = 182} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 2, ['y'] = 113} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 292, ['y'] = 157} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 147, ['y'] = 220} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 219, ['y'] = 98} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 133, ['y'] = 135} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 169, ['y'] = 135} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 34, ['y'] = 151} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 293, ['y'] = 188} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 124, ['y'] = 228} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 178, ['y'] = 228} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 270, ['y'] = 115 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 36, ['y'] = 120 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 223, ['y'] = 152 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 86, ['y'] = 161 }, ['dir'] = 'Right', },
        }
    },
    ['L9_3'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 146, ['y'] = 135} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 64, ['y'] = 103} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 147, ['y'] = 215} },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 119, ['y'] = 78 }, ['dir'] = 'Right', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 213, ['y'] = 119 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 116, ['y'] = 142 }, ['dir'] = 'Left', },
            { ['type'] = 'Mole', ['pos'] = { ['x'] = 62, ['y'] = 166 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 35, ['y'] = 118 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 199, ['y'] = 152 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 219, ['y'] = 182 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 290, ['y'] = 203 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 29, ['y'] = 207 }, ['dir'] = 'Right', },
        }
    },
    ['L10_1'] = {
        ['type'] = 'LevelE',
        ['entities'] = {
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 218, ['y'] = 82} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 62, ['y'] = 89} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 144, ['y'] = 113} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 61, ['y'] = 174} },
            { ['type'] = 'NormalRock', ['pos'] = { ['x'] = 178, ['y'] = 181} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 248, ['y'] = 98} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 23, ['y'] = 107} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 64, ['y'] = 131} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 218, ['y'] = 132} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 184, ['y'] = 135} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 69, ['y'] = 164} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 47, ['y'] = 154} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 124, ['y'] = 167} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 289, ['y'] = 177} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 89, ['y'] = 197} },
            { ['type'] = 'NormalGold', ['pos'] = { ['x'] = 202, ['y'] = 198} },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 258, ['y'] = 108 } },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 6, ['y'] = 134 } },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 162, ['y'] = 152 } },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 231, ['y'] = 209 } },
            { ['type'] = 'NormalGoldPlus', ['pos'] = { ['x'] = 66, ['y'] = 217 } },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 295, ['y'] = 145 } },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 219, ['y'] = 152 } },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 18, ['y'] = 176 } },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 123, ['y'] = 197 } },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 285, ['y'] = 210 } },
        }
    },
    ['L10_2'] = {
        ['type'] = 'LevelC',
        ['entities'] = {
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 211, ['y'] = 157} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 261, ['y'] = 185} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 17, ['y'] = 83} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 90, ['y'] = 83} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 209, ['y'] = 89} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 260, ['y'] = 134} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 119, ['y'] = 148} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 11, ['y'] = 180} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 182, ['y'] = 201} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 142, ['y'] = 88} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 48, ['y'] = 175} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 213, ['y'] = 182} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 122, ['y'] = 188} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 252, ['y'] = 212} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 105, ['y'] = 119} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 283, ['y'] = 120} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 246, ['y'] = 155} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 28, ['y'] = 163} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 168, ['y'] = 206} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 64, ['y'] = 220} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 36, ['y'] = 225} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 275, ['y'] = 102 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 44, ['y'] = 136 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 215, ['y'] = 147 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 85, ['y'] = 164 }, ['dir'] = 'Right', },
        }
    },
    ['L10_3'] = {
        ['type'] = 'LevelD',
        ['entities'] = {
            { ['type'] = 'Skull', ['pos'] = { ['x'] = 159, ['y'] = 178} },
            { ['type'] = 'Bone', ['pos'] = { ['x'] = 276, ['y'] = 193} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 95, ['y'] = 98} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 309, ['y'] = 160} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 23, ['y'] = 164} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 196, ['y'] = 175} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 145, ['y'] = 196} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 262, ['y'] = 209} },
            { ['type'] = 'TNT', ['pos'] = { ['x'] = 85, ['y'] = 218} },
            { ['type'] = 'MiniGold', ['pos'] = { ['x'] = 142, ['y'] = 88} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 48, ['y'] = 175} },
            { ['type'] = 'BigGold', ['pos'] = { ['x'] = 222, ['y'] = 222} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 5, ['y'] = 95} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 122, ['y'] = 188} },
            { ['type'] = 'QuestionBag', ['pos'] = { ['x'] = 280, ['y'] = 162} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 283, ['y'] = 120} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 305, ['y'] = 122} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 127, ['y'] = 127} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 247, ['y'] = 155} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 50, ['y'] = 157} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 299, ['y'] = 204} },
            { ['type'] = 'Diamond', ['pos'] = { ['x'] = 88, ['y'] = 206} },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 275, ['y'] = 102 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 44, ['y'] = 136 }, ['dir'] = 'Right', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 215, ['y'] = 147 }, ['dir'] = 'Left', },
            { ['type'] = 'MoleWithDiamond', ['pos'] = { ['x'] = 85, ['y'] = 164 }, ['dir'] = 'Right', },
        }
    },
}

function levels.loadLevel(realLevelStr, entities)
    if DEBUG_MODE and TEST_LEVEL then
        realLevelStr = 'LDEBUG'
    end
    for entityIndex, entity in ipairs(levels[realLevelStr].entities) do
        entityInstance = createEntityInstance(entity.type, entity.pos, entity.dir)
        table.insert(entities, entityInstance)
    end 
end

return levels