return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 40,
  height = 23,
  tilewidth = 8,
  tileheight = 8,
  nextlayerid = 11,
  nextobjectid = 505,
  properties = {
    ["name"] = "jungle_04"
  },
  tilesets = {
    {
      name = "collision",
      firstgid = 1,
      filename = "../../tiled_project/collision.tsx"
    },
    {
      name = "entities-sheet",
      firstgid = 17,
      filename = "../../tiled_project/entities-sheet.tsx"
    },
    {
      name = "spike-sheet",
      firstgid = 49,
      filename = "../../tiled_project/spike-sheet.tsx"
    },
    {
      name = "ground",
      firstgid = 53,
      filename = "../../tiled_project/ground.tsx"
    },
    {
      name = "trees",
      firstgid = 309,
      filename = "../../tiled_project/trees.tsx",
      exportfilename = "../tile_sets/trees.lua"
    },
    {
      name = "jungle",
      firstgid = 565,
      filename = "../../tiled_project/jungle.tsx"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../jungle-background.png",
      id = 10,
      name = "background",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      id = 1,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      id = 6,
      name = "back_1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 390, 393, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 390, 393, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 390, 393, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 390, 391, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 390, 393, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 406, 407, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 80, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 390, 391, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 406, 407, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 390, 391, 0, 0, 0, 0, 0, 390, 393, 0, 0, 390, 393, 0, 390, 393, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 406, 407, 0, 0, 0, 0, 0, 406, 409, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 390, 393, 0, 390, 393, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 406, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0,
        0, 390, 391, 392, 393, 0, 0, 390, 409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 390, 393, 0, 0, 390, 393, 0, 390, 393, 0, 0, 0, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0,
        0, 406, 407, 408, 409, 0, 0, 390, 393, 0, 0, 0, 0, 0, 0, 0, 0, 0, 406, 409, 0, 0, 406, 409, 0, 406, 409, 0, 0, 0, 0, 0, 406, 409, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      id = 4,
      name = "deco_1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 342, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 348, 349, 349, 350, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 348, 349, 311, 313, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 351, 352, 353, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 342, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 342, 351, 352, 353, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 358, 361, 0, 0, 0, 0, 0, 310, 313, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 0,
        310, 311, 312, 313, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 358, 361, 0, 0, 0, 0, 0, 0,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 310, 313, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 348, 349, 350, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        342, 343, 344, 345, 0, 0, 0, 0, 348, 349, 349, 350, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 366, 351, 352, 353, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 310, 313, 0, 0, 0, 0, 0, 342, 367, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        342, 343, 344, 351, 317, 318, 353, 0, 0, 0, 0, 342, 345, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 358, 361, 0, 0, 0, 0, 0, 310, 313, 0, 0, 0, 0, 0, 0,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 348, 349, 350, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 0,
        342, 343, 344, 345, 0, 0, 0, 0, 0, 0, 0, 342, 345, 0, 0, 0, 0, 0, 326, 351, 352, 353, 0, 0, 0, 0, 0, 0, 0, 348, 349, 317, 350, 345, 0, 0, 0, 310, 311, 312,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 358, 361, 0, 0, 0, 0, 0, 342, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 326, 327, 328,
        342, 343, 344, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 342, 351, 352, 353, 0, 326, 343, 344,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 342, 329, 0, 0, 0, 0, 0, 310, 313, 0, 0, 0, 0, 0, 358, 361, 0, 0, 0, 342, 327, 328,
        342, 343, 344, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 345, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 343, 344,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 310, 313, 0, 0, 0, 0, 0, 358, 361, 0, 0, 0, 348, 349, 350, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 342, 327, 328,
        342, 343, 344, 345, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 358, 361, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 343, 344,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 342, 351, 352, 353, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 310, 313, 0, 0, 0, 342, 327, 328,
        342, 343, 344, 345, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 326, 343, 344,
        326, 327, 328, 329, 0, 0, 0, 0, 0, 0, 0, 342, 345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 342, 345, 0, 0, 0, 342, 327, 328,
        342, 343, 344, 345, 0, 0, 0, 0, 0, 0, 0, 327, 328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 326, 329, 0, 0, 0, 326, 343, 344
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "entities",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 269,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 40,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 40,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 40,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 40,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 40,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 40,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 40,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 299,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 301,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 302,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 483,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 305,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 482,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 120,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 489,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 152,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 490,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 152,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 491,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 152,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 492,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 152,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 311,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 72,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 312,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 72,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 314,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 315,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 316,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 317,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 319,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 321,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 322,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 501,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 323,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 208,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 324,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 497,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 208,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 8,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 496,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 208,
          y = 176,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 346,
          name = "1-2",
          type = "door",
          shape = "rectangle",
          x = 8,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 21,
          visible = true,
          properties = {
            ["direction"] = 1,
            ["jumps_to_unlock"] = 0,
            ["spawn_pos_dx"] = 2,
            ["spawn_pos_dy"] = 0,
            ["target_door_name"] = "2-1",
            ["target_level_name"] = "dodge_falling_01",
            ["visible"] = true
          }
        },
        {
          id = 502,
          name = "2-1",
          type = "door",
          shape = "rectangle",
          x = 304,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 21,
          visible = true,
          properties = {
            ["direction"] = -1,
            ["jumps_to_unlock"] = 0,
            ["spawn_pos_dx"] = -1,
            ["spawn_pos_dy"] = 0,
            ["target_door_name"] = "1-2",
            ["target_level_name"] = "jungle_05",
            ["visible"] = true
          }
        },
        {
          id = 348,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 349,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 351,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 500,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 352,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 353,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 354,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 240,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 359,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 360,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 184,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 362,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 72,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 72,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 72,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 72,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 366,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 368,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 486,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 369,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 370,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 484,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 372,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 377,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 378,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 379,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 380,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 160,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 381,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 280,
          y = 168,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 382,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 383,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 120,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 128,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 136,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 494,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 144,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 168,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 224,
          y = 80,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 224,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 224,
          y = 96,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 487,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 224,
          y = 104,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "vine",
          shape = "rectangle",
          x = 224,
          y = 112,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 20,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "",
          type = "spawner",
          shape = "rectangle",
          x = 144,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {
            ["direction"] = 1,
            ["initial_time"] = 0,
            ["waiting_time"] = 4
          }
        },
        {
          id = 422,
          name = "",
          type = "snail",
          shape = "rectangle",
          x = 136,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 19,
          visible = true,
          properties = {
            ["direction"] = -1
          }
        },
        {
          id = 503,
          name = "3-1",
          type = "door",
          shape = "rectangle",
          x = 184,
          y = -5,
          width = 8,
          height = 8,
          rotation = 0,
          gid = 21,
          visible = true,
          properties = {
            ["direction"] = 1,
            ["jumps_to_unlock"] = 0,
            ["spawn_pos_dx"] = 0,
            ["spawn_pos_dy"] = 3,
            ["target_door_name"] = "1-3",
            ["target_level_name"] = "jungle_secret_01",
            ["visible"] = false
          }
        },
        {
          id = 504,
          name = "",
          type = "trigger",
          shape = "rectangle",
          x = 264,
          y = 72,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {
            ["expected_jumps"] = 0,
            ["id"] = "jumps",
            ["type"] = "JUMPS_SAVED_CUE"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "spikes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 391,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 40,
          y = 80,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 32,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 56,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 104,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 160,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 40,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 432,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 64,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 112,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 168,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 48,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 430,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 72,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 120,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 176,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 462,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 200,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 232,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 272,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 80,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 128,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 460,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 144,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 184,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 463,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 208,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 469,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 240,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 280,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 446,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 136,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 152,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 448,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 192,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 474,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 224,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 464,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 216,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 470,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 248,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 478,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 288,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 140,
          y = 44,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 196,
          y = 84,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 84,
          y = 100,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 52,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 196,
          y = 76,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 84,
          y = 92,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 410,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 44,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 196,
          y = 68,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 84,
          y = 84,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 36,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 28,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 140,
          y = 36,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 398,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 140,
          y = 28,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 392,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 44,
          y = 80,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 36,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 60,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 108,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 164,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 44,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 68,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 444,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 116,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 172,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 429,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 52,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 431,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 76,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 124,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 180,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 465,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 204,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 236,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 276,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 84,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 132,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 461,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 148,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 457,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 188,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 466,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 212,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 472,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 244,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 284,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 447,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 140,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 156,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 196,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 228,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 220,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 481,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 292,
          y = 184,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 140,
          y = 48,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 196,
          y = 88,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 84,
          y = 104,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 56,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 196,
          y = 80,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 84,
          y = 96,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 48,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 196,
          y = 72,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 84,
          y = 88,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 40,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 252,
          y = 32,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 140,
          y = 40,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "",
          type = "spike",
          shape = "rectangle",
          x = 140,
          y = 32,
          width = 4,
          height = 4,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 23,
      id = 5,
      name = "deco_2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 339, 340, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 165, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 323, 324, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    }
  }
}
