#!/bin/bash

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"
RUNDIR="$GAMEDIR"/game
SRCDIR="$GAMEDIR"/src
GAMEFILE="$SRCDIR"/game.zip

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1

echo "GAMEDIR is set to: $GAMEDIR"
echo "GAMEFILE is $GAMEFILE"

if [ ! -d "$RUNDIR" ]; then
  if [ ! -f "$GAMEFILE" ]; then
    pm_message "Game files not found"
    sleep 5
    exit 1
  fi

  echo "Extracting game files from $GAMEFILE"
  cd "$SRCDIR"
  unzip $GAMEFILE
  mv game $GAMEDIR/
  rm $GAMEFILE
else
  echo "Game files found."
fi
