# Machismo configuration for Crypt of the NecroDancer (Steam)
#
# Paths are relative to CWD (set by launch script to the port directory).

[general]
dylib_map = conf/dylib_map-steam.conf
patches = conf/patches/necrodancer.conf

[trampoline.sdl2]
lib = libSDL2-2.0.so.0
prefix = _SDL_

[trampoline.bgfx]
lib = libs/libbgfx-shared.so
prefix = _bgfx_
prefix = __ZN4bgfx
init_wrapper = true
renderer = opengles

[trampoline.steam_noop]
lib = STUB
prefix = __ZN3wos5steam
prefix = __ZNK3wos5steam
