#!/bin/bash

#
#   Gato Roboto update script
#   Author: kotzebuedog
#   Version: 1.0
#   Update from 5e4f49d installation
#   

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

cd "$GAMEDIR"

# -------------------- BEGIN FUNCTIONS --------------------

update_install_5e4f49d()
{

    echo "Renaming game.apk"
    mv "$GAMEDIR/game.apk" "$GAMEDIR/gatoroboto.port"
    [[ ! $? -eq 0 ]] && echo "Cannot rename game.apk" && return 1 # CRITICAL

    files_to_delete=(
        "gmloadernext"
        "lib/libcrypto.so.1.1"
        "lib/libopenal.so.1"
        "lib/libzip.so.5"
        "lib/armeabi-v7a"
    )

    for file in "${files_to_delete[@]}"; do
        echo "Deleting $file"
        rm -rf "$file"
    done

    return 0

}

# --------------------- END FUNCTIONS ---------------------

update_install_5e4f49d
[[ ! $? -eq 0 ]] && echo "Cannot update game" \
&& echo "Patching process failed!" && exit 1

echo "Game updated" && echo "Patching process done!" && exit 0
