#!/bin/bash

# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"
LOGERR="$GAMEDIR/patch_error.txt"

# Redirect output and error to the log file
rm -rf $LOGFILE $LOGERR
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/data"
export LD_LIBRARY_PATH="$GAMEDIR/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TMPDIR="$GAMEDIR/tmp"

# Permissions
chmod 666 /dev/uinput

cd "$GAMEDIR"

process_game() {
    export INSTALLER_EXE_GLOB="setup_the_elder_scrolls_iii_morrowind_*.exe"
    export INSTALLER_FILE_GLOB="setup_the_elder_scrolls_iii_morrowind_*"

    # Move installer to a safe place if it is in the $DATADIR
    for file in "$DATADIR"/$INSTALLER_FILE_GLOB; do
        if [ -f "$file" ]; then
            mv -fv "$file" "$GAMEDIR"
        fi
    done

    # Delete data directory.
    echo "Delete old data/ directory."
    rm -fRv "$DATADIR"

    # Extract files
    echo "Create temp directory."
    mkdir "$TMPDIR"
    cd $TMPDIR

    $GAMEDIR/innoextract.${DEVICE_ARCH} -I "Data Files" "$GAMEDIR"/$INSTALLER_EXE_GLOB

    echo "Move extracted files."
    mv -fv "Data Files" "$DATADIR"
    cd ..

    echo "Delete temp directory."
    rm -fRv "$TMPDIR"

    echo "Delete installer files."
    rm -fR "$GAMEDIR"/$INSTALLER_FILE_GLOB

    sleep 1

    # Final completion message
    echo "Patching process complete!"
}

process_game