name: Pull Request Check

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'tools/**'
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: false #only 1 build at a time per PR

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: hmarr/debug-action@v2
        name: "debug: ${{github.event_name}}"

      - name: Clean out files part 1
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v4

      - name: Clean out files part 2
        run: |
          rm -rf .git
          echo "Free Space"
          df -h

      - name: env - better defaulting of env vars;
        id: env
        run: |
            source SOURCE_SETUP.txt

            if [[ -z "$RELEASE_ORG" ]]; then
              echo "::error file=SOURCE_SETUP.txt,line=2::Missing RELEASE_ORG, please configure"
              exit 255
            fi
            echo "RELEASE_ORG=$RELEASE_ORG" >> $GITHUB_OUTPUT

            if [[ -z "$RELEASE_REPO" ]]; then
              echo "::error file=SOURCE_SETUP.txt,line=5::Missing RELEASE_REPO, please configure"
              exit 255
            fi
            echo "RELEASE_REPO=$RELEASE_REPO" >> $GITHUB_OUTPUT

            echo "PMGUI_RELEASE=$PMGUI_RELEASE" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          latest: true
          out-file-path: "releases"
          fileName: "*.json"

      - uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          latest: true
          out-file-path: "releases"
          fileName: "images.zip"

      - name: Generate Port Files.
        id: ports-info
        run: |
          touch .github_check
          python3 tools/build_data.py
          python3 tools/build_release.py --do-check

      - name: Check Free Space
        run: |
          df -h
