name: Safety Net
# This is just to make sure no one slips in a modified workflow or tools.

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'tools/**'
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Safety Check
        run: |
          exit 255
